"""Frozen verbatim copy of compute_team_shape / compute_defensive_line / _select_n at 05cfa56 -- the
ADR D12/D13 parity oracle (TF-58 Task 1). Never edit except an import path. Generated by
scratchpad/gen_oracle.py; the only change to each body is the legacy_ name prefix and the internal
_legacy_select_n call."""

from __future__ import annotations

from typing import Literal

import numpy as np
import pandas as pd
from scipy.cluster.hierarchy import fcluster, linkage
from scipy.spatial import ConvexHull, QhullError

from silly_kicks.id_compat import ids_match
from silly_kicks.tracking._gk_resolve import GoalEndUnresolvedError, GoalMap

__all__ = ["_legacy_select_n", "legacy_compute_defensive_line", "legacy_compute_team_shape"]

_RESULT_COLS = [
    "game_id",
    "period_id",
    "frame_id",
    "team_id",
    "n_outfield_players",
    "centroid_x",
    "centroid_y",
    "convex_hull_area",
    "team_length",
    "team_width",
    "stretch_index",
    "defensive_line_height",
    "inter_line_gap_1",
    "inter_line_gap_2",
]


def legacy_compute_team_shape(
    frames: pd.DataFrame,
    team_id: int | str,
    *,
    n_defensive_lines: int = 3,
) -> pd.DataFrame:
    """Per-(game_id, period_id, frame_id) team shape metrics for one team.

    Parameters
    ----------
    frames : pd.DataFrame
        Long-form tracking frames (TRACKING_FRAMES_COLUMNS schema).
    team_id : int | str
        Team to compute shape for.
    n_defensive_lines : int
        Number of defensive lines to identify via Ward clustering
        (default 3). Used for defensive_line_height and inter-line gaps.

    Returns
    -------
    pd.DataFrame
        One row per (game_id, period_id, frame_id) where the team has at
        least one visible outfield player. Frames with zero visible
        outfield players are omitted from output (consumers should LEFT
        JOIN and fill NaN). Columns: game_id, period_id, frame_id,
        team_id, n_outfield_players, centroid_x, centroid_y,
        convex_hull_area, team_length, team_width, stretch_index,
        defensive_line_height, inter_line_gap_1, inter_line_gap_2.

    Examples
    --------
    Compute team shape for a single team::

        from silly_kicks.tracking._team_shape import compute_team_shape
        shape = compute_team_shape(frames, team_id=1)

    See NOTICE for full bibliographic citations.
    """
    if len(frames) == 0:
        return pd.DataFrame(columns=_RESULT_COLS)

    # Filter to outfield players with valid coordinates
    mask = (
        ids_match(frames["team_id"], team_id)
        & (~frames["is_ball"].astype(bool))
        & (~frames["is_goalkeeper"].astype(bool))
        & frames["x"].notna()
        & frames["y"].notna()
    )
    outfield = frames[mask]
    if outfield.empty:
        return pd.DataFrame(columns=_RESULT_COLS)

    rows: list[dict] = []
    groups = outfield.groupby(["game_id", "period_id", "frame_id"], dropna=False)

    for (game_id, period_id, frame_id), group in groups:
        xs = group["x"].to_numpy(dtype="float64")
        ys = group["y"].to_numpy(dtype="float64")
        n = len(xs)

        cx = float(np.mean(xs))
        cy = float(np.mean(ys))
        team_length = float(np.max(xs) - np.min(xs))
        team_width = float(np.max(ys) - np.min(ys))

        # Stretch index: mean Euclidean distance from centroid
        dists = np.sqrt((xs - cx) ** 2 + (ys - cy) ** 2)
        stretch = float(np.mean(dists))

        # Convex hull area
        if n < 3:
            hull_area = np.nan
        else:
            try:
                hull = ConvexHull(np.column_stack([xs, ys]))
                hull_area = float(hull.volume)  # 2D: volume = area
            except QhullError:
                hull_area = 0.0  # collinear points -> degenerate hull with area 0

        # Defensive-line orientation (ADR-028): the deepest line is the cluster NEAREST
        # the team's defended goal. team_attacking_direction tells which goal the team
        # defends in these (home-attacks-right) frames: "ltr" attacks x=105 -> defends
        # x=0 -> deepest = lowest-x cluster; "rtl" attacks x=0 -> defends x=105 ->
        # deepest = highest-x cluster. Ordering from the deepest line outward makes
        # defensive_line_height + inter-line gaps the team's true defensive line for
        # BOTH teams (was min-x for everyone -> the away team's ADVANCED line). This is a
        # frame-level value; add_team_shape re-projects it to the per-action LTR frame.
        # Defaults to "ltr" (the historical behaviour) when direction is absent.
        direction = group["team_attacking_direction"].iloc[0] if "team_attacking_direction" in group.columns else None
        defends_high_x = direction == "rtl"

        # Ward hierarchical clustering for inter-line gaps (TF-44)
        n_eff = min(n_defensive_lines, n)
        if n < 2:
            def_line_height = float(xs.max() if defends_high_x else xs.min())
            gap_1 = np.nan
            gap_2 = np.nan
        else:
            z = linkage(xs.reshape(-1, 1), method="ward")
            labels = fcluster(z, t=n_eff, criterion="maxclust")
            # Cluster centroids, ordered from the DEEPEST line (nearest the defended goal)
            # outward. Ascending for ltr (deepest = min-x); reversed for rtl (deepest = max-x).
            centroids = np.sort([float(np.mean(xs[labels == c])) for c in range(1, n_eff + 1) if np.any(labels == c)])
            if defends_high_x:
                centroids = centroids[::-1]
            n_actual = len(centroids)
            def_line_height = float(centroids[0])
            gap_1 = float(abs(centroids[1] - centroids[0])) if n_actual >= 2 else np.nan
            gap_2 = float(abs(centroids[2] - centroids[1])) if n_actual >= 3 else np.nan

        rows.append(
            {
                "game_id": game_id,
                "period_id": period_id,
                "frame_id": frame_id,
                "team_id": team_id,
                "n_outfield_players": n,
                "centroid_x": cx,
                "centroid_y": cy,
                "convex_hull_area": hull_area,
                "team_length": team_length,
                "team_width": team_width,
                "stretch_index": stretch,
                "defensive_line_height": def_line_height,
                "inter_line_gap_1": gap_1,
                "inter_line_gap_2": gap_2,
            }
        )

    result = pd.DataFrame(rows, columns=_RESULT_COLS)
    result["n_outfield_players"] = result["n_outfield_players"].astype("Int64")
    return result


def legacy_compute_defensive_line(
    frames: pd.DataFrame,
    *,
    goal_map: GoalMap,
    n: int | Literal["adaptive"] = 4,
    adaptive_max_n: int = 5,
) -> pd.DataFrame:
    """Per-(game_id, period_id, frame_id, team_id): 6 back-line geometry columns.

    Computes for BOTH teams, so it needs BOTH ends -- which is why it takes the map
    rather than a single direction bool (the ADR-051 D3 rule: one team -> bool, both
    teams -> map).

    Parameters
    ----------
    frames : pd.DataFrame
        Long-form tracking frames (TRACKING_FRAMES_COLUMNS shape).
        Must be LTR-normalized (play_left_to_right applied).
    goal_map : GoalMap
        Per-(game, period, team) defended-goal ends, built ONCE per match from the FULL
        frames (:func:`resolve_defended_goals`). REQUIRED, no default: a default would
        re-admit per-frame direction inference at exactly the call sites that forget it.
        An unresolved end RAISES :class:`GoalEndUnresolvedError` rather than guessing.
    n : int | Literal["adaptive"], default 4
        Target back-line player count (3, 4, or 5), clamped to available
        outfield players (minimum 3). Or "adaptive" for x-gap clustering.
    adaptive_max_n : int, default 5
        Upper bound for adaptive N. Must be in {3, 4, 5}.

    Returns
    -------
    pd.DataFrame
        Columns: game_id, period_id, frame_id, team_id, defensive_line_x,
        back_line_high_x, compactness_x, lateral_width, max_lateral_gap,
        back_n_count.

    Raises
    ------
    ValueError
        If n is an int outside {3, 4, 5}, adaptive_max_n outside {3, 4, 5},
        frames missing required columns, or non-LTR direction values found.

    Examples
    --------
    Compute defensive-line geometry for both teams::

        from silly_kicks.tracking.features import compute_defensive_line
        goal_map = resolve_defended_goals(frames)   # ONCE per match, full frames
        dl = compute_defensive_line(frames, goal_map=goal_map, n=4)

    See NOTICE for full bibliographic citations.
    """
    # --- Validation ---
    if isinstance(n, int) and n not in (3, 4, 5):
        raise ValueError(f"n must be 3, 4, or 5 (got {n})")
    if adaptive_max_n not in (3, 4, 5):
        raise ValueError(f"adaptive_max_n must be in {{3, 4, 5}} (got {adaptive_max_n})")

    required_cols = {"game_id", "period_id", "frame_id", "team_id", "player_id", "is_ball", "is_goalkeeper", "x", "y"}
    missing = required_cols - set(frames.columns)
    if missing:
        raise ValueError(f"compute_defensive_line: frames missing columns {sorted(missing)}")

    # LTR guard: period-normalized frames have home="ltr", away="rtl"
    if "team_attacking_direction" in frames.columns:
        directions = set(frames["team_attacking_direction"].dropna().unique())
        valid = {"ltr", "rtl"}
        unexpected = directions - valid
        if unexpected:
            raise ValueError(
                "compute_defensive_line: frames have unexpected "
                f"team_attacking_direction values: {sorted(unexpected)}. "
                "Expected 'ltr'/'rtl' only."
            )
        if directions and "ltr" not in directions:
            raise ValueError(
                "compute_defensive_line: frames must be period-normalized "
                "(play_left_to_right). Found only 'rtl' direction values — "
                "no home-team rows with 'ltr'."
            )

    # --- Short-circuit ---
    result_cols = [
        "game_id",
        "period_id",
        "frame_id",
        "team_id",
        "defensive_line_x",
        "back_line_high_x",
        "compactness_x",
        "lateral_width",
        "max_lateral_gap",
        "back_n_count",
    ]
    if len(frames) == 0:
        return pd.DataFrame(columns=result_cols)

    # --- Core computation ---
    # Filter to outfield players with valid coordinates
    outfield = frames[(~frames["is_ball"]) & (~frames["is_goalkeeper"]) & frames["x"].notna()].copy()

    # Group by (game_id, period_id, frame_id, team_id)
    rows: list[dict] = []
    groups = outfield.groupby(["game_id", "period_id", "frame_id", "team_id"], dropna=False)

    for (game_id, period_id, frame_id, team_id), group in groups:
        p = len(group)
        if p < 3:
            rows.append(
                {
                    "game_id": game_id,
                    "period_id": period_id,
                    "frame_id": frame_id,
                    "team_id": team_id,
                    "defensive_line_x": np.nan,
                    "back_line_high_x": np.nan,
                    "compactness_x": np.nan,
                    "lateral_width": np.nan,
                    "max_lateral_gap": np.nan,
                    "back_n_count": pd.NA,
                }
            )
            continue

        # Sort by proximity to own goal. Direction comes from the GoalMap, never from team
        # IDENTITY: `same_id(team_id, home_team_id)` is correct only while the frames are
        # home-attacks-right and silently inverts otherwise (ADR-051 D3).
        own_end = goal_map.get(game_id, period_id, team_id, allow_guess=True)
        if own_end is None:
            # Explicit: `== 0.0` alone would fail OPEN, silently choosing 'defends x=0'.
            raise GoalEndUnresolvedError(
                f"defensive line: goal_map does not resolve the end defended by {team_id!r} "
                f"in (game={game_id!r}, period={period_id!r})."
            )
        defends_x0 = own_end == 0.0
        xs = group["x"].to_numpy(dtype="float64")
        ys = group["y"].to_numpy(dtype="float64")

        if defends_x0:
            order = np.argsort(xs)  # ascending: closest to x=0 first
        else:
            order = np.argsort(-xs)  # descending: closest to x=105 first

        xs_sorted = xs[order]
        ys_sorted = ys[order]

        # Determine N
        n_effective = _legacy_select_n(xs_sorted, n, adaptive_max_n, p)

        # Select back-line players
        sel_x = xs_sorted[:n_effective]
        sel_y = ys_sorted[:n_effective]

        # Compute 6 columns
        defensive_line_x = float(np.mean(sel_x))
        compactness_x = float(np.max(sel_x) - np.min(sel_x))

        if defends_x0:
            back_line_high_x = float(np.max(sel_x))  # furthest from x=0
        else:
            back_line_high_x = float(np.min(sel_x))  # furthest from x=105

        lateral_width = float(np.max(sel_y) - np.min(sel_y))

        # max_lateral_gap: sort by y, compute adjacent gaps
        y_sorted = np.sort(sel_y)
        if len(y_sorted) >= 2:
            y_gaps = np.diff(y_sorted)
            max_lateral_gap = float(np.max(y_gaps))
        else:
            max_lateral_gap = 0.0

        rows.append(
            {
                "game_id": game_id,
                "period_id": period_id,
                "frame_id": frame_id,
                "team_id": team_id,
                "defensive_line_x": defensive_line_x,
                "back_line_high_x": back_line_high_x,
                "compactness_x": compactness_x,
                "lateral_width": lateral_width,
                "max_lateral_gap": max_lateral_gap,
                "back_n_count": n_effective,
            }
        )

    result = pd.DataFrame(rows, columns=result_cols)
    result["back_n_count"] = result["back_n_count"].astype("Int64")
    return result


def _legacy_select_n(
    xs_sorted: np.ndarray,
    n: int | Literal["adaptive"],
    adaptive_max_n: int,
    p: int,
) -> int:
    """Determine how many players form the back line.

    Parameters
    ----------
    xs_sorted : sorted x-positions (closest to own goal first)
    n : target N or "adaptive"
    adaptive_max_n : upper bound for adaptive
    p : total available outfield players

    Returns
    -------
    int : effective N (3..5, clamped to available)
    """
    if isinstance(n, int):
        return min(n, p)

    # --- Adaptive algorithm ---
    if p == 3:
        return 3
    if p == 4:
        # Single cut-point; no relative comparison possible -> default N=4
        return 4

    # Examine cut-points: gaps between positions [2]->[3], [3]->[4], [4]->[5]
    gaps = np.diff(xs_sorted)  # gaps[i] = xs_sorted[i+1] - xs_sorted[i]

    # Available cut indices (0-indexed into gaps array):
    # cut at [2]->[3] means gaps[2]; corresponds to N=3
    # cut at [3]->[4] means gaps[3]; corresponds to N=4
    # cut at [4]->[5] means gaps[4]; corresponds to N=5
    cut_indices = []
    cut_ns = []
    for candidate_n in (3, 4, 5):
        gap_idx = candidate_n - 1  # gaps[2] = gap between sorted[2] and sorted[3] -> N=3
        if gap_idx < len(gaps) and candidate_n <= adaptive_max_n:
            cut_indices.append(gap_idx)
            cut_ns.append(candidate_n)

    if not cut_indices:
        return min(4, p)

    cut_gaps = [abs(float(gaps[i])) for i in cut_indices]

    # Degenerate: all gaps are 0
    if max(cut_gaps) == 0.0:
        return min(4, p)

    # Find dominant gap
    sorted_gaps = sorted(cut_gaps, reverse=True)
    max_gap = sorted_gaps[0]
    second_gap = sorted_gaps[1] if len(sorted_gaps) > 1 else 0.0

    if second_gap == 0.0 or max_gap >= 1.5 * second_gap:
        # Dominant gap found
        best_idx = cut_gaps.index(max_gap)
        return cut_ns[best_idx]

    # No dominant gap -> default to 4
    return min(4, p)
