"""Opponent-mirror upgrade gate (ADR-041, spec A6).

The 4.24.0 opponent perspective mirrored the transition/EPV artifacts along x only
(``np.flip(..., axis=1)``). That is exactly right for the y-SYMMETRIC synthetic grids but
wrong for an injected, y-asymmetric xT-derived surface, where the faithful transform for
"the opponent attacks the other goal" is a point reflection (both axes).

Measured on this tree @ ec543cc (numbers pasted per the CLAUDE.md rule -- claims about a
numeric property carry the measurement):

* ``_make_synthetic_epv_grid``          : EXACTLY flipud-symmetric (a tiled x-ramp).
* ``_make_synthetic_reachability_grid`` : symmetric to 4.440892098500626e-16 across
  3752/6400 cells (``np.linspace`` ULP amplified by ``exp``).
* ``_interpolate_grid`` at the REAL (32, 50) target: carries that to 3.331e-16
  (5.551e-16 at (68, 104)). Symmetrizing the SOURCE does NOT improve it -- still
  3.331e-16 -- which is why production is deliberately left untouched.

So the axis change is a no-op on the synthetic path at the 1e-16 level, while a structural
regression (wrong axis, real registration offset) is O(1). ``space_created_m2`` is an AREA
in m^2 (cell 4.4625, pitch 7140), so the tolerance is RELATIVE: an absolute ``atol`` tight
enough to be meaningful at unit scale is far below the computation's own float noise at
area scale.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from silly_kicks.tracking import features as F
from silly_kicks.tracking._obso import (
    _interpolate_grid,
    _make_synthetic_epv_grid,
    _make_synthetic_reachability_grid,
)
from silly_kicks.tracking._space_creation import compute_space_created
from tests.tracking._space_creation_mirror_fixture import build_mirror_fixture

_GOLDEN_PATH = Path(__file__).parent / "fixtures" / "space_creation_mirror_golden.npz"

# ADR-041 opt-out: this module deliberately exercises the synthetic placeholder EPV path
# (the default surface is the subject of the identity gate below).
pytestmark = pytest.mark.filterwarnings("ignore::silly_kicks.tracking.SyntheticEPVWarning")


class TestSyntheticNoiseFloor:
    """Pins the measured floor so a STRUCTURAL symmetry break fails HERE, not silently."""

    def test_epv_grid_is_exactly_symmetric(self):
        epv = _make_synthetic_epv_grid()
        np.testing.assert_array_equal(epv, np.flipud(epv))

    def test_reachability_symmetry_is_float_noise_only(self):
        reach = _make_synthetic_reachability_grid()
        asym = np.abs(reach - np.flipud(reach)).max()
        assert 0.0 < asym < 1e-14, f"reachability y-asymmetry left the float-noise band: {asym}"

    def test_resampled_symmetry_at_the_real_target_shape(self):
        """(32, 50) is the shape space_creation actually resamples to."""
        reach = _make_synthetic_reachability_grid()
        resampled = _interpolate_grid(reach, (32, 50))
        assert np.abs(resampled - np.flipud(resampled)).max() < 1e-14


class TestOpponentMirrorIdentityOnSyntheticPath:
    """THE gate: output pinned to values captured on the PRE-change tree (plan Task 0).

    Not a self-comparison -- the golden .npz was generated by
    scripts/gen_space_creation_mirror_golden.py before the axis change, and its generator
    refuses to write an all-NaN or all-zero golden (both would pass vacuously).
    """

    def test_golden_is_non_vacuous(self):
        g = np.load(_GOLDEN_PATH)
        created = g["space_created_m2"]
        assert np.isfinite(created).any()
        assert np.any(np.abs(created[np.isfinite(created)]) > 0.0), (
            "all-zero golden would make the identity gate pass under ANY change"
        )

    def test_output_unchanged_by_the_mirror_upgrade(self):
        g = np.load(_GOLDEN_PATH)
        actions, frames = build_mirror_fixture()
        out = F.add_space_creation(actions, frames, home_team_id=5)
        np.testing.assert_allclose(
            out["space_created_m2"].to_numpy(dtype=float),
            g["space_created_m2"],
            rtol=1e-9,
            atol=0,
        )
        np.testing.assert_allclose(
            out["space_denied_m2_opponent"].to_numpy(dtype=float),
            g["space_denied_m2_opponent"],
            rtol=1e-9,
            atol=0,
        )


_LOW_Y_PID, _HIGH_Y_PID = 11, 12


def _y_mirrored_frame() -> pd.DataFrame:
    """Two EQUALLY marginal attackers at the same x, at mirrored y (14 and 54).

    Built from measurements, because three earlier geometries were vacuous: a
    leave-one-out is identically 0 for mutually-redundant players (a tight cluster covers
    itself) AND for an uncontested one (measured 1.4e-10 at any defender gap from 4 to
    11 m) -- a player is marginal only when a defender sits ~5-6 m away. The goalkeeper
    otherwise dominates the denial sum, and sits at y=34, exactly ON the mirror axis, so
    it cannot discriminate a y-flip at all.

    On the synthetic path the two probes are measured EXACTLY equal (0.253886 each),
    which is what makes the y-ramp comparison below attributable to the transform alone.
    """

    def row(pid, team, gk, x, y, is_ball=False):
        return {
            "game_id": 1,
            "period_id": 1,
            "frame_id": 100,
            "time_seconds": 4.0,
            "frame_rate": 25.0,
            "player_id": pid,
            "team_id": team,
            "is_ball": is_ball,
            "is_goalkeeper": gk,
            "x": float(np.clip(x, 0.5, 104.5)),
            "y": float(np.clip(y, 0.5, 67.5)),
            "z": 0.0,
            "speed": 1.5,
            "vx": 1.5,
            "vy": 0.0,
            "speed_source": "native",
            "ball_state": "alive",
            "team_attacking_direction": "ltr" if team == 5 else "rtl",
            "confidence": None,
            "visibility": None,
            "source_provider": "gradientsports",
            "is_goalkeeper_source": "native",
        }

    return pd.DataFrame(
        [
            row(None, None, False, 32.0, 34.0, is_ball=True),
            row(_LOW_Y_PID, 5, False, 30.0, 14.0),
            row(21, 6, False, 34.0, 18.0),  # ~5.7 m: makes the low-y probe marginal
            row(_HIGH_Y_PID, 5, False, 30.0, 54.0),
            row(22, 6, False, 34.0, 50.0),  # ~5.7 m: mirror-image contest
            row(1, 5, True, 6.0, 34.0),
            row(2, 6, True, 99.0, 34.0),
        ]
    )


class TestPointReflectionDiscriminator:
    """Proves the change is NOT vacuous: an asymmetric injected grid must reflect BOTH axes.

    The identity gate above cannot see this -- it runs the y-SYMMETRIC synthetic path by
    construction, where the two transforms agree to 1e-16 -- so this test carries the whole
    discriminating burden and is built to invert between the implementations.

    Method: inject an EPV grid that varies ONLY in y (constant in x). The x-flip is then a
    no-op on it, which isolates the row axis exactly -- the one thing the change touches:

    * old ``axis=1``      -> rows unchanged, so the opponent multiplier keeps the ramp's
      orientation and the HIGH-y attacker is denied more;
    * ``axis=(0, 1)``     -> rows flipped, so the multiplier's ramp inverts and the LOW-y
      attacker is denied more.

    Measured pre-change: low_y 0.248629 vs high_y 0.960876 (3.87x the wrong way round), so
    ``low_y > high_y`` is genuinely RED before the change and GREEN after -- verified, not
    assumed.
    """

    @staticmethod
    def _denials() -> tuple[float, float]:
        # EPV increasing with y, constant in x -> the x-flip cannot affect this comparison.
        epv = np.tile(np.linspace(0.02, 1.0, 68).reshape(-1, 1), (1, 104))
        res = compute_space_created(
            _y_mirrored_frame(),
            attacking_team_id=5,
            epv_grid=epv,
            include_opponent_perspective=True,
        ).set_index("player_id")
        denial = res["space_denied_m2_opponent"]
        return float(denial.loc[float(_LOW_Y_PID)]), float(denial.loc[float(_HIGH_Y_PID)])

    def test_probes_are_symmetric_on_the_synthetic_path(self):
        """Sanity: the two probes are interchangeable until an asymmetric EPV is injected.

        Without this, a difference below could come from the geometry rather than from the
        transform under test.
        """
        res = compute_space_created(
            _y_mirrored_frame(), attacking_team_id=5, include_opponent_perspective=True
        ).set_index("player_id")
        d = res["space_denied_m2_opponent"]
        lo, hi = float(d.loc[float(_LOW_Y_PID)]), float(d.loc[float(_HIGH_Y_PID)])
        assert lo > 0.0, "probes are not marginal controllers - the comparison is vacuous"
        assert lo == pytest.approx(hi, rel=1e-9)

    def test_opponent_multiplier_reflects_the_row_axis(self):
        low_y, high_y = self._denials()
        assert min(low_y, high_y) > 0.0, "no opponent denial for either probe - the discriminator is vacuous"
        assert low_y > high_y, (
            "opponent multiplier did not invert its y-ramp: the row axis is not being "
            f"reflected (low_y={low_y:.6g} <= high_y={high_y:.6g})"
        )
