"""CI tests for the real-data-calibrated ``realistic.parquet`` synthetic fixtures.

The fixtures are generated by ``tests/datasets/tracking/{provider}/
generate_synthetic.py`` with ``inject_realistic_edge_cases=True`` and the
provider's empirical baseline. They cover edge cases the strict
deterministic fixtures do not: small fraction of off-pitch player rows,
ball-out interval, ball-x throw-in tail, NaN ball coordinates (when the
provider's baseline shows a non-trivial NaN rate).

These tests verify the adapters handle the edge cases without crashing
or producing schema-violating output, with the same realistic tolerance
the e2e real-data sweep applies (98% in-bounds rather than 100%).
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from silly_kicks.tracking.schema import (
    GRADIENTSPORTS_TRACKING_FRAMES_COLUMNS,
    SPORTEC_TRACKING_FRAMES_COLUMNS,
    TRACKING_CONSTRAINTS,
    TrackingConversionReport,
)

_FIX = Path(__file__).resolve().parent / "datasets" / "tracking"


def _bounds_check_loose(frames: pd.DataFrame, provider: str) -> None:
    """98%-bounds check matching the real-data sweep tolerance."""
    for col, (lo, hi) in TRACKING_CONSTRAINTS.items():
        if col not in frames.columns:
            continue
        vals = frames[col].dropna()
        if len(vals) == 0:
            continue
        if hi == float("inf"):
            assert (vals >= lo).all(), f"{provider}/{col}: values below {lo}"
        else:
            in_bounds = vals.between(lo, hi).mean()
            assert in_bounds >= 0.98, f"{provider}/{col}: only {in_bounds:.4f} of values in [{lo}, {hi}]"


def test_sportec_realistic_fixture_round_trips():
    raw = pd.read_parquet(_FIX / "sportec" / "realistic.parquet")
    from silly_kicks.tracking.sportec import convert_to_frames

    frames, report = convert_to_frames(
        raw,
        home_team_id="DFL-CLU-0100",
        home_team_start_left=True,
    )
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(SPORTEC_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "sportec")


def test_sportec_realistic_fixture_has_ball_out_interval():
    raw = pd.read_parquet(_FIX / "sportec" / "realistic.parquet")
    from silly_kicks.tracking.sportec import convert_to_frames

    _, report = convert_to_frames(
        raw,
        home_team_id="DFL-CLU-0100",
        home_team_start_left=True,
    )
    # Empirical-baseline edge cases include a ball-out interval; report
    # should record non-zero ball-dead seconds in the active period.
    assert any(v > 0 for v in report.ball_out_seconds_per_period.values()), (
        f"expected ball-out interval, got {report.ball_out_seconds_per_period}"
    )


def test_gradientsports_realistic_fixture_round_trips():
    raw = pd.read_parquet(_FIX / "gradientsports" / "realistic.parquet")
    from silly_kicks.tracking.gradientsports import convert_to_frames

    frames, report = convert_to_frames(
        raw,
        home_team_id=100,
        home_team_start_left=True,
    )
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(GRADIENTSPORTS_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "gradientsports")


def test_gradientsports_realistic_fixture_off_pitch_player_tolerated():
    raw = pd.read_parquet(_FIX / "gradientsports" / "realistic.parquet")
    # The empirical baseline shows ~0.35% of player y rows off-pitch in real
    # Gradient Sports data; the synthetic generator injects this rate. The conversion
    # should not crash, and the off-pitch tail in output (after coordinate
    # translation) should be non-empty.
    from silly_kicks.tracking.gradientsports import convert_to_frames

    frames, _ = convert_to_frames(
        raw,
        home_team_id=100,
        home_team_start_left=True,
    )
    out_of_y = (~frames["y"].between(0, 68)).sum()
    assert out_of_y > 0, "expected some off-pitch y values from injected edge cases"


@pytest.mark.parametrize("provider", ["sportec", "gradientsports"])
def test_realistic_fixture_total_input_frames_in_report(provider):
    raw = pd.read_parquet(_FIX / provider / "realistic.parquet")
    if provider == "sportec":
        from silly_kicks.tracking.sportec import convert_to_frames

        _, report = convert_to_frames(
            raw,
            home_team_id="DFL-CLU-0100",
            home_team_start_left=True,
        )
    else:
        from silly_kicks.tracking.gradientsports import convert_to_frames

        _, report = convert_to_frames(
            raw,
            home_team_id=100,
            home_team_start_left=True,
        )
    assert report.total_input_frames == raw["frame_id"].nunique()


def test_metrica_realistic_dataset_round_trips():
    from datasets.tracking.metrica.generate_synthetic import (
        build_metrica_tracking_dataset,
    )

    from silly_kicks.tracking.kloppy import convert_to_frames
    from silly_kicks.tracking.schema import KLOPPY_TRACKING_FRAMES_COLUMNS

    ds = build_metrica_tracking_dataset(n_frames=300, inject_realistic_edge_cases=True)
    frames, report = convert_to_frames(ds)
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(KLOPPY_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "metrica")


def test_skillcorner_realistic_dataset_round_trips():
    from datasets.tracking.skillcorner.generate_synthetic import (
        build_skillcorner_tracking_dataset,
    )

    from silly_kicks.tracking.kloppy import convert_to_frames
    from silly_kicks.tracking.schema import KLOPPY_TRACKING_FRAMES_COLUMNS

    ds = build_skillcorner_tracking_dataset(n_frames=200, inject_realistic_edge_cases=True)
    frames, report = convert_to_frames(ds)
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(KLOPPY_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "skillcorner")


def test_kloppy_gk_derivation_fires_when_native_wrong():
    """Verify GK derivation fires when kloppy's native is_goalkeeper is wrong.

    Real Metrica/SkillCorner kloppy parsers set starting_position=Unknown,
    so is_goalkeeper is always False. This test creates a dataset with
    intentionally wrong native GK flags (mimicking real parser behavior)
    and verifies the algorithm derives the correct GKs.
    """
    import datetime

    from kloppy.domain import (  # type: ignore[import-not-found]
        CustomCoordinateSystem,
        DatasetFlag,
        Dimension,
        Frame,
        Ground,
        Metadata,
        MetricPitchDimensions,
        Orientation,
        Origin,
        Period,
        Player,
        PlayerData,
        Point,
        Point3D,
        PositionType,
        Provider,
        Team,
        TrackingDataset,
        VerticalOrientation,
    )

    from silly_kicks.tracking.kloppy import convert_to_frames

    # Build dataset where ALL players have starting_position=Unknown (no native GK flag)
    home_team = Team(team_id="home", name="Home", ground=Ground.HOME)
    away_team = Team(team_id="away", name="Away", ground=Ground.AWAY)

    # GK is jersey 1, but we set starting_position=Unknown for ALL players
    home_team.players = [
        Player(
            player_id=f"h_{i}",
            team=home_team,
            jersey_no=i,
            first_name="H",
            last_name=str(i),
            starting_position=PositionType.Unknown,  # intentionally wrong
        )
        for i in range(11)
    ]
    away_team.players = [
        Player(
            player_id=f"a_{i}",
            team=away_team,
            jersey_no=i,
            first_name="A",
            last_name=str(i),
            starting_position=PositionType.Unknown,  # intentionally wrong
        )
        for i in range(11)
    ]

    period = Period(
        id=1,
        start_timestamp=datetime.timedelta(seconds=0),
        end_timestamp=datetime.timedelta(seconds=4),
    )
    pitch = MetricPitchDimensions(
        x_dim=Dimension(0, 105.0),
        y_dim=Dimension(0, 68.0),
        standardized=False,
        pitch_length=105.0,
        pitch_width=68.0,
    )
    # Real kloppy provider datasets always carry a coordinate_system; the tracking gateway pins the
    # canonical SPADL CS off it (ADR-031). Declare the synthetic source coords as already-canonical
    # (BOTTOM_LEFT/BOTTOM_TO_TOP 105x68), so the CS-pin is a no-op and this GK-derivation test (which
    # asserts on x positions) is unaffected.
    coord_system = CustomCoordinateSystem(
        origin=Origin.BOTTOM_LEFT,
        vertical_orientation=VerticalOrientation.BOTTOM_TO_TOP,
        pitch_dimensions=pitch,
    )
    metadata = Metadata(
        teams=[home_team, away_team],
        periods=[period],
        pitch_dimensions=pitch,
        coordinate_system=coord_system,
        score=None,
        frame_rate=25.0,
        orientation=Orientation.HOME_AWAY,
        flags=DatasetFlag.BALL_OWNING_TEAM,
        provider=Provider.METRICA,
        game_id="gk_derivation_test",
    )

    # Build 100 frames with GKs (jersey 0) positioned near goal
    frames = []
    for fid in range(100):
        ts = datetime.timedelta(seconds=fid / 25.0)
        players_data = {}

        # Home players: jersey 0 is GK at x=5 (near goal)
        for i, player in enumerate(home_team.players):
            x = 5.0 if i == 0 else 40.0 + i * 3
            y = 34.0
            players_data[player] = PlayerData(coordinates=Point(x=x, y=y), distance=None, speed=1.0)

        # Away players: jersey 0 is GK at x=100 (near goal at x=105)
        # Outfielders at x=20-47 (far from their goal, not in PA)
        for i, player in enumerate(away_team.players):
            x = 100.0 if i == 0 else 20.0 + i * 3
            y = 34.0
            players_data[player] = PlayerData(coordinates=Point(x=x, y=y), distance=None, speed=1.0)

        frames.append(
            Frame(
                period=period,
                timestamp=ts,
                statistics=[],
                ball_owning_team=home_team,
                ball_state=None,
                frame_id=fid,
                players_data=players_data,
                other_data={},
                ball_coordinates=Point3D(x=52.5, y=34.0, z=0.0),
                ball_speed=5.0,
            )
        )

    ds = TrackingDataset(metadata=metadata, records=frames)
    result_frames, report = convert_to_frames(ds, output_convention="absolute_frame")

    # Verify derivation fired (kloppy had no native GK flags)
    assert report.n_teams_gk_derived == 2, f"Expected 2 teams with derived GK, got {report.n_teams_gk_derived}"
    assert len(report.derived_gk_picks) == 2

    # Verify correct GKs were picked (jersey 0 = player_id h_0 and a_0)
    assert set(report.derived_gk_picks[("gk_derivation_test", "home")]) == {"h_0"}
    assert set(report.derived_gk_picks[("gk_derivation_test", "away")]) == {"a_0"}

    # Verify is_goalkeeper_source == "derived" for all player rows
    player_rows = result_frames[~result_frames["is_ball"]]
    assert (player_rows["is_goalkeeper_source"] == "derived").all()


def test_metrica_realistic_dataset_off_pitch_player_tolerated():
    """The empirical baseline shows real Metrica data has small off-pitch
    tail; the realistic kloppy dataset variant injects this. The gateway
    should not crash, and the output should contain some off-pitch tail
    after coordinate translation."""
    from datasets.tracking.metrica.generate_synthetic import (
        build_metrica_tracking_dataset,
    )

    from silly_kicks.tracking.kloppy import convert_to_frames

    ds = build_metrica_tracking_dataset(n_frames=400, inject_realistic_edge_cases=True)
    frames, _ = convert_to_frames(ds)
    out_of_y = (~frames["y"].between(0, 68)).sum()
    assert out_of_y > 0, "expected some off-pitch y values from injected edge cases"


# ---------------------------------------------------------------------------
# Lakehouse-derived CI tests: load committed real-data slices and run them
# through the same adapter / gateway code paths the e2e sweep exercises.
# Slim parquets (~50 KB each, license-permissive open-data providers) live
# under tests/datasets/tracking/<provider>/lakehouse_derived.parquet.
# Built via scripts/build_lakehouse_ci_fixtures.py (one-off developer run).
# ---------------------------------------------------------------------------


def test_sportec_lakehouse_derived_round_trips():
    fixture = _FIX / "sportec" / "lakehouse_derived.parquet"
    if not fixture.exists():
        pytest.skip(f"{fixture} not committed yet --- regenerate via scripts/build_lakehouse_ci_fixtures.py")
    raw = pd.read_parquet(fixture)
    from datasets.tracking._lakehouse_adapter import lakehouse_to_sportec_input

    sportec_input = lakehouse_to_sportec_input(raw).dropna(subset=["x_centered", "y_centered"])
    from silly_kicks.tracking.sportec import convert_to_frames

    home_team_str = str(sportec_input.loc[~sportec_input["is_ball"], "team_id"].dropna().iloc[0])
    frames, report = convert_to_frames(
        sportec_input,
        home_team_id=home_team_str,
        home_team_start_left=True,
    )
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(SPORTEC_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "sportec")


def test_metrica_lakehouse_derived_round_trips():
    fixture = _FIX / "metrica" / "lakehouse_derived.parquet"
    if not fixture.exists():
        pytest.skip(f"{fixture} not committed yet --- regenerate via scripts/build_lakehouse_ci_fixtures.py")
    raw = pd.read_parquet(fixture)
    from datasets.tracking._lakehouse_adapter import lakehouse_to_kloppy_dataset
    from kloppy.domain import Provider  # type: ignore[import-not-found]

    from silly_kicks.tracking.kloppy import convert_to_frames
    from silly_kicks.tracking.schema import KLOPPY_TRACKING_FRAMES_COLUMNS

    ds = lakehouse_to_kloppy_dataset(raw, Provider.METRICA)
    assert len(ds.records) > 0, "metrica lakehouse fixture yielded no frames"
    frames, report = convert_to_frames(ds)
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(KLOPPY_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "metrica")


def test_skillcorner_lakehouse_derived_round_trips():
    fixture = _FIX / "skillcorner" / "lakehouse_derived.parquet"
    if not fixture.exists():
        pytest.skip(f"{fixture} not committed yet --- regenerate via scripts/build_lakehouse_ci_fixtures.py")
    raw = pd.read_parquet(fixture)
    from datasets.tracking._lakehouse_adapter import lakehouse_to_kloppy_dataset
    from kloppy.domain import Provider  # type: ignore[import-not-found]

    from silly_kicks.tracking.kloppy import convert_to_frames
    from silly_kicks.tracking.schema import KLOPPY_TRACKING_FRAMES_COLUMNS

    ds = lakehouse_to_kloppy_dataset(raw, Provider.SKILLCORNER)
    assert len(ds.records) > 0, "skillcorner lakehouse fixture yielded no frames"
    frames, report = convert_to_frames(ds)
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(KLOPPY_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "skillcorner")
