"""CI tests for the real-data-calibrated ``realistic.parquet`` synthetic fixtures.

The fixtures are generated by ``tests/datasets/tracking/{provider}/
generate_synthetic.py`` with ``inject_realistic_edge_cases=True`` and the
provider's empirical baseline. They cover edge cases the strict
deterministic fixtures do not: small fraction of off-pitch player rows,
ball-out interval, ball-x throw-in tail, NaN ball coordinates (when the
provider's baseline shows a non-trivial NaN rate).

These tests verify the adapters handle the edge cases without crashing
or producing schema-violating output, with the same realistic tolerance
the e2e real-data sweep applies (98% in-bounds rather than 100%).
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from silly_kicks.tracking.schema import (
    PFF_TRACKING_FRAMES_COLUMNS,
    SPORTEC_TRACKING_FRAMES_COLUMNS,
    TRACKING_CONSTRAINTS,
    TrackingConversionReport,
)

_FIX = Path(__file__).resolve().parent / "datasets" / "tracking"


def _bounds_check_loose(frames: pd.DataFrame, provider: str) -> None:
    """98%-bounds check matching the real-data sweep tolerance."""
    for col, (lo, hi) in TRACKING_CONSTRAINTS.items():
        if col not in frames.columns:
            continue
        vals = frames[col].dropna()
        if len(vals) == 0:
            continue
        if hi == float("inf"):
            assert (vals >= lo).all(), f"{provider}/{col}: values below {lo}"
        else:
            in_bounds = vals.between(lo, hi).mean()
            assert in_bounds >= 0.98, f"{provider}/{col}: only {in_bounds:.4f} of values in [{lo}, {hi}]"


def test_sportec_realistic_fixture_round_trips():
    raw = pd.read_parquet(_FIX / "sportec" / "realistic.parquet")
    from silly_kicks.tracking.sportec import convert_to_frames

    frames, report = convert_to_frames(
        raw,
        home_team_id="DFL-CLU-0100",
        home_team_start_left=True,
    )
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(SPORTEC_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "sportec")


def test_sportec_realistic_fixture_has_ball_out_interval():
    raw = pd.read_parquet(_FIX / "sportec" / "realistic.parquet")
    from silly_kicks.tracking.sportec import convert_to_frames

    _, report = convert_to_frames(
        raw,
        home_team_id="DFL-CLU-0100",
        home_team_start_left=True,
    )
    # Empirical-baseline edge cases include a ball-out interval; report
    # should record non-zero ball-dead seconds in the active period.
    assert any(v > 0 for v in report.ball_out_seconds_per_period.values()), (
        f"expected ball-out interval, got {report.ball_out_seconds_per_period}"
    )


def test_pff_realistic_fixture_round_trips():
    raw = pd.read_parquet(_FIX / "pff" / "realistic.parquet")
    from silly_kicks.tracking.pff import convert_to_frames

    frames, report = convert_to_frames(
        raw,
        home_team_id=100,
        home_team_start_left=True,
    )
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(PFF_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "pff")


def test_pff_realistic_fixture_off_pitch_player_tolerated():
    raw = pd.read_parquet(_FIX / "pff" / "realistic.parquet")
    # The empirical baseline shows ~0.35% of player y rows off-pitch in real
    # PFF data; the synthetic generator injects this rate. The conversion
    # should not crash, and the off-pitch tail in output (after coordinate
    # translation) should be non-empty.
    from silly_kicks.tracking.pff import convert_to_frames

    frames, _ = convert_to_frames(
        raw,
        home_team_id=100,
        home_team_start_left=True,
    )
    out_of_y = (~frames["y"].between(0, 68)).sum()
    assert out_of_y > 0, "expected some off-pitch y values from injected edge cases"


@pytest.mark.parametrize("provider", ["sportec", "pff"])
def test_realistic_fixture_total_input_frames_in_report(provider):
    raw = pd.read_parquet(_FIX / provider / "realistic.parquet")
    if provider == "sportec":
        from silly_kicks.tracking.sportec import convert_to_frames

        _, report = convert_to_frames(
            raw,
            home_team_id="DFL-CLU-0100",
            home_team_start_left=True,
        )
    else:
        from silly_kicks.tracking.pff import convert_to_frames

        _, report = convert_to_frames(
            raw,
            home_team_id=100,
            home_team_start_left=True,
        )
    assert report.total_input_frames == raw["frame_id"].nunique()


def test_metrica_realistic_dataset_round_trips():
    from datasets.tracking.metrica.generate_synthetic import (
        build_metrica_tracking_dataset,
    )

    from silly_kicks.tracking.kloppy import convert_to_frames
    from silly_kicks.tracking.schema import KLOPPY_TRACKING_FRAMES_COLUMNS

    ds = build_metrica_tracking_dataset(n_frames=300, inject_realistic_edge_cases=True)
    frames, report = convert_to_frames(ds)
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(KLOPPY_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "metrica")


def test_skillcorner_realistic_dataset_round_trips():
    from datasets.tracking.skillcorner.generate_synthetic import (
        build_skillcorner_tracking_dataset,
    )

    from silly_kicks.tracking.kloppy import convert_to_frames
    from silly_kicks.tracking.schema import KLOPPY_TRACKING_FRAMES_COLUMNS

    ds = build_skillcorner_tracking_dataset(n_frames=200, inject_realistic_edge_cases=True)
    frames, report = convert_to_frames(ds)
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(KLOPPY_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "skillcorner")


def test_metrica_realistic_dataset_off_pitch_player_tolerated():
    """The empirical baseline shows real Metrica data has small off-pitch
    tail; the realistic kloppy dataset variant injects this. The gateway
    should not crash, and the output should contain some off-pitch tail
    after coordinate translation."""
    from datasets.tracking.metrica.generate_synthetic import (
        build_metrica_tracking_dataset,
    )

    from silly_kicks.tracking.kloppy import convert_to_frames

    ds = build_metrica_tracking_dataset(n_frames=400, inject_realistic_edge_cases=True)
    frames, _ = convert_to_frames(ds)
    out_of_y = (~frames["y"].between(0, 68)).sum()
    assert out_of_y > 0, "expected some off-pitch y values from injected edge cases"


# ---------------------------------------------------------------------------
# Lakehouse-derived CI tests: load committed real-data slices and run them
# through the same adapter / gateway code paths the e2e sweep exercises.
# Slim parquets (~50 KB each, license-permissive open-data providers) live
# under tests/datasets/tracking/<provider>/lakehouse_derived.parquet.
# Built via scripts/build_lakehouse_ci_fixtures.py (one-off developer run).
# ---------------------------------------------------------------------------


def test_sportec_lakehouse_derived_round_trips():
    fixture = _FIX / "sportec" / "lakehouse_derived.parquet"
    if not fixture.exists():
        pytest.skip(f"{fixture} not committed yet --- regenerate via scripts/build_lakehouse_ci_fixtures.py")
    raw = pd.read_parquet(fixture)
    from datasets.tracking._lakehouse_adapter import lakehouse_to_sportec_input

    sportec_input = lakehouse_to_sportec_input(raw).dropna(subset=["x_centered", "y_centered"])
    from silly_kicks.tracking.sportec import convert_to_frames

    home_team_str = str(sportec_input.loc[~sportec_input["is_ball"], "team_id"].dropna().iloc[0])
    frames, report = convert_to_frames(
        sportec_input,
        home_team_id=home_team_str,
        home_team_start_left=True,
    )
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(SPORTEC_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "sportec")


def test_metrica_lakehouse_derived_round_trips():
    fixture = _FIX / "metrica" / "lakehouse_derived.parquet"
    if not fixture.exists():
        pytest.skip(f"{fixture} not committed yet --- regenerate via scripts/build_lakehouse_ci_fixtures.py")
    raw = pd.read_parquet(fixture)
    from datasets.tracking._lakehouse_adapter import lakehouse_to_kloppy_dataset
    from kloppy.domain import Provider

    from silly_kicks.tracking.kloppy import convert_to_frames
    from silly_kicks.tracking.schema import KLOPPY_TRACKING_FRAMES_COLUMNS

    ds = lakehouse_to_kloppy_dataset(raw, Provider.METRICA)
    assert len(ds.records) > 0, "metrica lakehouse fixture yielded no frames"
    frames, report = convert_to_frames(ds)
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(KLOPPY_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "metrica")


def test_skillcorner_lakehouse_derived_round_trips():
    fixture = _FIX / "skillcorner" / "lakehouse_derived.parquet"
    if not fixture.exists():
        pytest.skip(f"{fixture} not committed yet --- regenerate via scripts/build_lakehouse_ci_fixtures.py")
    raw = pd.read_parquet(fixture)
    from datasets.tracking._lakehouse_adapter import lakehouse_to_kloppy_dataset
    from kloppy.domain import Provider

    from silly_kicks.tracking.kloppy import convert_to_frames
    from silly_kicks.tracking.schema import KLOPPY_TRACKING_FRAMES_COLUMNS

    ds = lakehouse_to_kloppy_dataset(raw, Provider.SKILLCORNER)
    assert len(ds.records) > 0, "skillcorner lakehouse fixture yielded no frames"
    frames, report = convert_to_frames(ds)
    assert isinstance(report, TrackingConversionReport)
    assert set(frames.columns) == set(KLOPPY_TRACKING_FRAMES_COLUMNS)
    _bounds_check_loose(frames, "skillcorner")
