"""Standard-SPADL-specific framework helpers — ``play_left_to_right`` and
``feature_column_names``. Both hardcode standard SPADL columns
(``start_x`` / ``end_x`` / ``result_id`` / ``result_name``) so they don't
generalize to atomic SPADL; atomic has its own equivalents in
``silly_kicks.atomic.vaep.features``.

Re-exports the framework primitives from ``silly_kicks.vaep.feature_framework``
so existing ``from silly_kicks.vaep.features.core import gamestates`` paths
continue to resolve (Hyrum's Law preservation).
"""

import numpy as np  # type: ignore
import pandas as pd  # type: ignore

import silly_kicks.spadl.config as spadlcfg
from silly_kicks.vaep.feature_framework import (
    Actions,
    Features,
    FeatureTransfomer,
    GameStates,
    actiontype_categorical,
    gamestates,
    is_frame_aware,
    simple,
)

__all__ = [
    "Actions",
    "FeatureTransfomer",
    "Features",
    "GameStates",
    "actiontype_categorical",
    "feature_column_names",
    "gamestates",
    "play_left_to_right",
    "simple",
]


def _empty_tracking_frames() -> pd.DataFrame:
    """Build an empty long-form tracking frames DataFrame for column-name probing.

    Used by ``feature_column_names`` to call frame-aware xfns at column-discovery
    time without requiring real frames. Frame-aware xfns generated by
    ``lift_to_states`` write their output column names without inspecting frames'
    contents (they iterate per gamestate slot), so an empty DataFrame is sufficient.
    """
    cols = [
        "game_id",
        "period_id",
        "frame_id",
        "time_seconds",
        "frame_rate",
        "player_id",
        "team_id",
        "is_ball",
        "is_goalkeeper",
        "x",
        "y",
        "z",
        "speed",
        "speed_source",
        "ball_state",
        "team_attacking_direction",
        "confidence",
        "visibility",
        "source_provider",
    ]
    return pd.DataFrame({c: pd.Series(dtype="object") for c in cols})


def feature_column_names(fs: list[FeatureTransfomer], nb_prev_actions: int = 3) -> list[str]:
    """Return the names of the features generated by a list of transformers.

    Parameters
    ----------
    fs : list(callable)
        A list of feature transformers. Frame-aware transformers (marked via
        ``@frame_aware`` or produced by ``silly_kicks.tracking.feature_framework.lift_to_states``)
        are called with an empty tracking-frames DataFrame; their output column
        names are derived from the gamestate slots and don't depend on frames'
        contents.
    nb_prev_actions : int, default=3  # noqa: DAR103
        The number of previous actions included in the game state.

    Returns
    -------
    list(str)
        The name of each generated feature.

    Examples
    --------
    Discover the feature column names a feature-fn list will produce::

        from silly_kicks.vaep import features as fs

        cols = fs.feature_column_names([fs.actiontype_onehot, fs.bodypart_onehot])
        # cols includes the cartesian product of feature x previous-action index.
    """
    spadlcolumns = [
        "game_id",
        "original_event_id",
        "action_id",
        "period_id",
        "time_seconds",
        "team_id",
        "player_id",
        "start_x",
        "start_y",
        "end_x",
        "end_y",
        "result_id",
        "result_name",
        "bodypart_id",
        "bodypart_name",
        "type_id",
        "type_name",
    ]
    dummy_actions = pd.DataFrame(np.zeros((10, len(spadlcolumns))), columns=spadlcolumns)
    for c in spadlcolumns:
        if "name" in c:
            dummy_actions[c] = dummy_actions[c].astype(str)
    gs = gamestates(dummy_actions, nb_prev_actions)  # type: ignore
    empty_frames = _empty_tracking_frames()
    parts = []
    for f in fs:
        if is_frame_aware(f):
            parts.append(f(gs, empty_frames))  # type: ignore[call-arg]  # frame-aware xfn has wider signature than FeatureTransfomer alias
        else:
            parts.append(f(gs))
    return list(pd.concat(parts, axis=1).columns.values)


def play_left_to_right(gamestates: GameStates, home_team_id: int) -> GameStates:
    """Mirror away-team gamestate rows from absolute-frame to SPADL LTR convention.

    Public boundary helper for callers who have absolute-frame-home-right
    gamestates (home plays LTR, away plays RTL in absolute coordinates) and
    want to convert them to the canonical SPADL "all teams attack
    left-to-right" convention. Mirrors ``(start_x, start_y) / (end_x, end_y)``
    of every row whose ``a0.team_id != home_team_id``.

    .. versionchanged:: 3.0.0
        Pre-3.0.0, ``vaep.base.VAEP.compute_features`` called this function
        unconditionally on every input. ADR-006 / PR-S22 removed that internal
        call because every silly-kicks 3.0.0+ converter outputs canonical SPADL
        LTR by default -- the second mirror inverted away-team rows for
        absolute-frame providers and accidentally compensated for a converter
        bug in possession-perspective providers. This function is retained as
        a public utility for external callers who load gamestates from outside
        silly-kicks; internal call sites no longer use it.

    Parameters
    ----------
    gamestates : GameStates
        Gamestates in absolute-frame-home-right convention.
    home_team_id : int
        ID of the home team. Determines which rows are away rows that need
        mirroring.

    Returns
    -------
    GameStates
        Gamestates with all actions performed left-to-right.

    See Also
    --------
    silly_kicks.spadl.play_left_to_right : Equivalent transform on a flat actions DataFrame.
    silly_kicks.spadl.to_spadl_ltr : Canonical normalizer used inside converters.

    Examples
    --------
    Convert externally-loaded absolute-frame gamestates to SPADL LTR::

        from silly_kicks.vaep.features import play_left_to_right

        ltr_states = play_left_to_right(absolute_frame_states, home_team_id=100)
        # Every away-team gamestate now has flipped (start_x, start_y) / (end_x, end_y).
    """
    a0 = gamestates[0]
    away_idx = a0.team_id != home_team_id
    for actions in gamestates:
        for col in ["start_x", "end_x"]:
            actions.loc[away_idx, col] = spadlcfg.field_length - actions[away_idx][col].values  # type: ignore[reportAttributeAccessIssue]
        for col in ["start_y", "end_y"]:
            actions.loc[away_idx, col] = spadlcfg.field_width - actions[away_idx][col].values  # type: ignore[reportAttributeAccessIssue]
    return gamestates
