"""Standard-SPADL-specific framework helpers — ``play_left_to_right`` and
``feature_column_names``. Both hardcode standard SPADL columns
(``start_x`` / ``end_x`` / ``result_id`` / ``result_name``) so they don't
generalize to atomic SPADL; atomic has its own equivalents in
``silly_kicks.atomic.vaep.features``.

Re-exports the framework primitives from ``silly_kicks.vaep.feature_framework``
so existing ``from silly_kicks.vaep.features.core import gamestates`` paths
continue to resolve (Hyrum's Law preservation).
"""

import numpy as np  # type: ignore
import pandas as pd  # type: ignore

import silly_kicks.spadl.config as spadlcfg
from silly_kicks.vaep.feature_framework import (
    Actions,
    Features,
    FeatureTransfomer,
    GameStates,
    actiontype_categorical,
    gamestates,
    simple,
)

__all__ = [
    "Actions",
    "FeatureTransfomer",
    "Features",
    "GameStates",
    "actiontype_categorical",
    "feature_column_names",
    "gamestates",
    "play_left_to_right",
    "simple",
]


def feature_column_names(fs: list[FeatureTransfomer], nb_prev_actions: int = 3) -> list[str]:
    """Return the names of the features generated by a list of transformers.

    Parameters
    ----------
    fs : list(callable)
        A list of feature transformers.
    nb_prev_actions : int, default=3  # noqa: DAR103
        The number of previous actions included in the game state.

    Returns
    -------
    list(str)
        The name of each generated feature.

    Examples
    --------
    Discover the feature column names a feature-fn list will produce::

        from silly_kicks.vaep import features as fs

        cols = fs.feature_column_names([fs.actiontype_onehot, fs.bodypart_onehot])
        # cols includes the cartesian product of feature x previous-action index.
    """
    spadlcolumns = [
        "game_id",
        "original_event_id",
        "action_id",
        "period_id",
        "time_seconds",
        "team_id",
        "player_id",
        "start_x",
        "start_y",
        "end_x",
        "end_y",
        "result_id",
        "result_name",
        "bodypart_id",
        "bodypart_name",
        "type_id",
        "type_name",
    ]
    dummy_actions = pd.DataFrame(np.zeros((10, len(spadlcolumns))), columns=spadlcolumns)
    for c in spadlcolumns:
        if "name" in c:
            dummy_actions[c] = dummy_actions[c].astype(str)
    gs = gamestates(dummy_actions, nb_prev_actions)  # type: ignore
    return list(pd.concat([f(gs) for f in fs], axis=1).columns.values)


def play_left_to_right(gamestates: GameStates, home_team_id: int) -> GameStates:
    """Perform all actions in a gamestate in the same playing direction.

    This changes the start and end location of each action in a gamestate,
    such that all actions are performed as if the team that performs the first
    action in the gamestate plays from left to right.

    Parameters
    ----------
    gamestates : GameStates
        The game states of a game.
    home_team_id : int
        The ID of the home team.

    Returns
    -------
    GameStates
        The game states with all actions performed left to right.

    See Also
    --------
    silly_kicks.spadl.play_left_to_right : For transforming actions.

    Examples
    --------
    Mirror gamestates to a single direction (per home_team_id)::

        from silly_kicks.vaep.features import play_left_to_right

        ltr_states = play_left_to_right(states, home_team_id=100)
        # Every away-team gamestate now has flipped (start_x, start_y) / (end_x, end_y).
    """
    a0 = gamestates[0]
    away_idx = a0.team_id != home_team_id
    for actions in gamestates:
        for col in ["start_x", "end_x"]:
            actions.loc[away_idx, col] = spadlcfg.field_length - actions[away_idx][col].values  # type: ignore[reportAttributeAccessIssue]
        for col in ["start_y", "end_y"]:
            actions.loc[away_idx, col] = spadlcfg.field_width - actions[away_idx][col].values  # type: ignore[reportAttributeAccessIssue]
    return gamestates
