"""SB360 verdicts -- shape family.

Observations and applicability classes are TRANSCRIBED FROM EXECUTION; only a
human writes an adjudication or a rationale.
"""

from __future__ import annotations

import silly_kicks.tracking as T
from tests.sb360 import _calls as C
from tests.sb360._registry import AxisVerdict, _entry

_entry(
    "add_defensive_line",
    C.generic(T.add_defensive_line),
    columns=(
        "defensive_line_x",
        "back_line_high_x",
        "compactness_x",
        "lateral_width",
        "max_lateral_gap",
        "back_n_count",
    ),
    velocity={
        "defensive_line_x": AxisVerdict("identical", "works"),
        "back_line_high_x": AxisVerdict("identical", "works"),
        "compactness_x": AxisVerdict("identical", "works"),
        "lateral_width": AxisVerdict("identical", "works"),
        "max_lateral_gap": AxisVerdict("identical", "works"),
        "back_n_count": AxisVerdict("identical", "works"),
    },
    visibility={
        "gk_absent": {
            "defensive_line_x": AxisVerdict("identical", "works"),
            "back_line_high_x": AxisVerdict("identical", "works"),
            "compactness_x": AxisVerdict("identical", "works"),
            "lateral_width": AxisVerdict("identical", "works"),
            "max_lateral_gap": AxisVerdict("identical", "works"),
            "back_n_count": AxisVerdict("identical", "works"),
        },
        "defender_absent": {
            "defensive_line_x": AxisVerdict("identical", "works"),
            "back_line_high_x": AxisVerdict("identical", "works"),
            "compactness_x": AxisVerdict("identical", "works"),
            "lateral_width": AxisVerdict("identical", "works"),
            "max_lateral_gap": AxisVerdict("identical", "works"),
            "back_n_count": AxisVerdict("identical", "works"),
        },
    },
    applicability={
        "defensive_line_x": "no_support",
        "back_line_high_x": "no_support",
        "compactness_x": "no_support",
        "lateral_width": "no_support",
        "max_lateral_gap": "no_support",
        "back_n_count": "no_support",
    },
    applicability_deltas={
        "defensive_line_x": {"extreme": 0.0, "near": 0.0},
        "back_line_high_x": {"extreme": 0.0, "near": 0.0},
        "compactness_x": {"extreme": 0.0, "near": 0.0},
        "lateral_width": {"extreme": 0.0, "near": 0.0},
        "max_lateral_gap": {"extreme": 0.0, "near": 0.0},
        "back_n_count": {"extreme": 0.0, "near": 0.0},
    },
)

_entry(
    "add_line_break",
    C.generic(T.add_line_break),
    columns=(
        "line_break",
        "n_attackers_behind_line",
    ),
    velocity={
        "line_break": AxisVerdict("identical", "works"),
        "n_attackers_behind_line": AxisVerdict("identical", "works"),
    },
    visibility={
        "gk_absent": {
            "line_break": AxisVerdict("identical", "works"),
            "n_attackers_behind_line": AxisVerdict("identical", "works"),
        },
        "defender_absent": {
            "line_break": AxisVerdict("identical", "works"),
            "n_attackers_behind_line": AxisVerdict("identical", "works"),
        },
    },
    applicability={
        "line_break": "no_support",
        "n_attackers_behind_line": "no_support",
    },
    applicability_deltas={
        "line_break": {"extreme": 0.0, "near": 0.0},
        "n_attackers_behind_line": {"extreme": 0.0, "near": 0.0},
    },
)

_entry(
    "add_packing",
    C.generic(T.add_packing),
    columns=(
        "packing_made",
        "packing_net",
        "packing_goal_threat",
        "packing_receiver_player_id",
        "packing_secured",
    ),
    velocity={
        "packing_made": AxisVerdict("identical", "works"),
        "packing_net": AxisVerdict("identical", "works"),
        "packing_goal_threat": AxisVerdict("identical", "works"),
        "packing_receiver_player_id": AxisVerdict("identical", "works"),
        "packing_secured": AxisVerdict("identical", "works"),
    },
    visibility={
        "gk_absent": {
            "packing_made": AxisVerdict("identical", "works"),
            "packing_net": AxisVerdict("identical", "works"),
            "packing_goal_threat": AxisVerdict("identical", "works"),
            "packing_receiver_player_id": AxisVerdict("identical", "works"),
            "packing_secured": AxisVerdict("identical", "works"),
        },
        "defender_absent": {
            "packing_made": AxisVerdict("identical", "works"),
            "packing_net": AxisVerdict("identical", "works"),
            "packing_goal_threat": AxisVerdict("identical", "works"),
            "packing_receiver_player_id": AxisVerdict("identical", "works"),
            "packing_secured": AxisVerdict("identical", "works"),
        },
    },
    applicability={
        "packing_made": "no_support",
        "packing_net": "no_support",
        "packing_goal_threat": "no_support",
        "packing_receiver_player_id": "no_support",
        "packing_secured": "no_support",
    },
    applicability_deltas={
        "packing_made": {"extreme": 0.0, "near": 0.0},
        "packing_net": {"extreme": 0.0, "near": 0.0},
        "packing_goal_threat": {"extreme": 0.0, "near": 0.0},
        "packing_receiver_player_id": {"extreme": 0.0, "near": 0.0},
        "packing_secured": {"extreme": 0.0, "near": 0.0},
    },
)

_entry(
    "add_shape_graph",
    C.generic(T.add_shape_graph),
    columns=(
        "shape_graph_density_attacking",
        "shape_graph_density_defending",
        "shape_graph_n_edges_attacking",
        "shape_graph_n_edges_defending",
        "shape_graph_mean_stability_attacking",
        "shape_graph_mean_stability_defending",
    ),
    velocity={
        "shape_graph_density_attacking": AxisVerdict("identical", "works"),
        "shape_graph_density_defending": AxisVerdict("identical", "works"),
        "shape_graph_n_edges_attacking": AxisVerdict("identical", "works"),
        "shape_graph_n_edges_defending": AxisVerdict("identical", "works"),
        "shape_graph_mean_stability_attacking": AxisVerdict("identical", "works"),
        "shape_graph_mean_stability_defending": AxisVerdict("identical", "works"),
    },
    visibility={
        "gk_absent": {
            "shape_graph_density_attacking": AxisVerdict("identical", "works"),
            "shape_graph_density_defending": AxisVerdict("identical", "works"),
            "shape_graph_n_edges_attacking": AxisVerdict("identical", "works"),
            "shape_graph_n_edges_defending": AxisVerdict("identical", "works"),
            "shape_graph_mean_stability_attacking": AxisVerdict("identical", "works"),
            "shape_graph_mean_stability_defending": AxisVerdict("identical", "works"),
        },
        "defender_absent": {
            "shape_graph_density_attacking": AxisVerdict("identical", "works"),
            "shape_graph_density_defending": AxisVerdict("identical", "works"),
            "shape_graph_n_edges_attacking": AxisVerdict("identical", "works"),
            "shape_graph_n_edges_defending": AxisVerdict("identical", "works"),
            "shape_graph_mean_stability_attacking": AxisVerdict("identical", "works"),
            "shape_graph_mean_stability_defending": AxisVerdict("identical", "works"),
        },
    },
    applicability={
        "shape_graph_density_attacking": "no_support",
        "shape_graph_density_defending": "no_support",
        "shape_graph_n_edges_attacking": "no_support",
        "shape_graph_n_edges_defending": "no_support",
        "shape_graph_mean_stability_attacking": "no_support",
        "shape_graph_mean_stability_defending": "no_support",
    },
    applicability_deltas={
        "shape_graph_density_attacking": {"extreme": 0.0, "near": 0.0},
        "shape_graph_density_defending": {"extreme": 0.0, "near": 0.0},
        "shape_graph_n_edges_attacking": {"extreme": 0.0, "near": 0.0},
        "shape_graph_n_edges_defending": {"extreme": 0.0, "near": 0.0},
        "shape_graph_mean_stability_attacking": {"extreme": 0.0, "near": 0.0},
        "shape_graph_mean_stability_defending": {"extreme": 0.0, "near": 0.0},
    },
)

_entry(
    "add_structural_pass",
    C.generic(T.add_structural_pass),
    columns=(
        "structural_lbs",
        "structural_sgm",
        "structural_sdi",
    ),
    velocity={
        "structural_lbs": AxisVerdict("identical", "works"),
        "structural_sgm": AxisVerdict("identical", "works"),
        "structural_sdi": AxisVerdict("identical", "works"),
    },
    visibility={
        "gk_absent": {
            "structural_lbs": AxisVerdict("identical", "works"),
            "structural_sgm": AxisVerdict("identical", "works"),
            "structural_sdi": AxisVerdict("identical", "works"),
        },
        "defender_absent": {
            "structural_lbs": AxisVerdict("identical", "works"),
            "structural_sgm": AxisVerdict("identical", "works"),
            "structural_sdi": AxisVerdict("identical", "works"),
        },
    },
    applicability={
        "structural_lbs": "no_support",
        "structural_sgm": "no_support",
        "structural_sdi": "no_support",
    },
    applicability_deltas={
        "structural_lbs": {"extreme": 0.0, "near": 0.0},
        "structural_sgm": {"extreme": 0.0, "near": 0.0},
        "structural_sdi": {"extreme": 0.0, "near": 0.0},
    },
)

_entry(
    "add_team_shape",
    C.generic(T.add_team_shape),
    columns=(
        "team_shape_n_outfield_players_attacking",
        "team_shape_centroid_x_attacking",
        "team_shape_centroid_y_attacking",
        "team_shape_convex_hull_area_attacking",
        "team_shape_team_length_attacking",
        "team_shape_team_width_attacking",
        "team_shape_stretch_index_attacking",
        "team_shape_defensive_line_height_attacking",
        "team_shape_inter_line_gap_1_attacking",
        "team_shape_inter_line_gap_2_attacking",
        "team_shape_n_outfield_players_defending",
        "team_shape_centroid_x_defending",
        "team_shape_centroid_y_defending",
        "team_shape_convex_hull_area_defending",
        "team_shape_team_length_defending",
        "team_shape_team_width_defending",
        "team_shape_stretch_index_defending",
        "team_shape_defensive_line_height_defending",
        "team_shape_inter_line_gap_1_defending",
        "team_shape_inter_line_gap_2_defending",
    ),
    velocity={
        "team_shape_n_outfield_players_attacking": AxisVerdict("identical", "works"),
        "team_shape_centroid_x_attacking": AxisVerdict("identical", "works"),
        "team_shape_centroid_y_attacking": AxisVerdict("identical", "works"),
        "team_shape_convex_hull_area_attacking": AxisVerdict("identical", "works"),
        "team_shape_team_length_attacking": AxisVerdict("identical", "works"),
        "team_shape_team_width_attacking": AxisVerdict("identical", "works"),
        "team_shape_stretch_index_attacking": AxisVerdict("identical", "works"),
        "team_shape_defensive_line_height_attacking": AxisVerdict("identical", "works"),
        "team_shape_inter_line_gap_1_attacking": AxisVerdict("identical", "works"),
        "team_shape_inter_line_gap_2_attacking": AxisVerdict("identical", "works"),
        "team_shape_n_outfield_players_defending": AxisVerdict("identical", "works"),
        "team_shape_centroid_x_defending": AxisVerdict("identical", "works"),
        "team_shape_centroid_y_defending": AxisVerdict("identical", "works"),
        "team_shape_convex_hull_area_defending": AxisVerdict("identical", "works"),
        "team_shape_team_length_defending": AxisVerdict("identical", "works"),
        "team_shape_team_width_defending": AxisVerdict("identical", "works"),
        "team_shape_stretch_index_defending": AxisVerdict("identical", "works"),
        "team_shape_defensive_line_height_defending": AxisVerdict("identical", "works"),
        "team_shape_inter_line_gap_1_defending": AxisVerdict("identical", "works"),
        "team_shape_inter_line_gap_2_defending": AxisVerdict("identical", "works"),
    },
    visibility={
        "gk_absent": {
            "team_shape_n_outfield_players_attacking": AxisVerdict("identical", "works"),
            "team_shape_centroid_x_attacking": AxisVerdict("identical", "works"),
            "team_shape_centroid_y_attacking": AxisVerdict("identical", "works"),
            "team_shape_convex_hull_area_attacking": AxisVerdict("identical", "works"),
            "team_shape_team_length_attacking": AxisVerdict("identical", "works"),
            "team_shape_team_width_attacking": AxisVerdict("identical", "works"),
            "team_shape_stretch_index_attacking": AxisVerdict("identical", "works"),
            "team_shape_defensive_line_height_attacking": AxisVerdict("identical", "works"),
            "team_shape_inter_line_gap_1_attacking": AxisVerdict("identical", "works"),
            "team_shape_inter_line_gap_2_attacking": AxisVerdict("identical", "works"),
            "team_shape_n_outfield_players_defending": AxisVerdict("identical", "works"),
            "team_shape_centroid_x_defending": AxisVerdict("identical", "works"),
            "team_shape_centroid_y_defending": AxisVerdict("identical", "works"),
            "team_shape_convex_hull_area_defending": AxisVerdict("identical", "works"),
            "team_shape_team_length_defending": AxisVerdict("identical", "works"),
            "team_shape_team_width_defending": AxisVerdict("identical", "works"),
            "team_shape_stretch_index_defending": AxisVerdict("identical", "works"),
            "team_shape_defensive_line_height_defending": AxisVerdict("identical", "works"),
            "team_shape_inter_line_gap_1_defending": AxisVerdict("identical", "works"),
            "team_shape_inter_line_gap_2_defending": AxisVerdict("identical", "works"),
        },
        "defender_absent": {
            "team_shape_n_outfield_players_attacking": AxisVerdict("identical", "works"),
            "team_shape_centroid_x_attacking": AxisVerdict("identical", "works"),
            "team_shape_centroid_y_attacking": AxisVerdict("identical", "works"),
            "team_shape_convex_hull_area_attacking": AxisVerdict("identical", "works"),
            "team_shape_team_length_attacking": AxisVerdict("identical", "works"),
            "team_shape_team_width_attacking": AxisVerdict("identical", "works"),
            "team_shape_stretch_index_attacking": AxisVerdict("identical", "works"),
            "team_shape_defensive_line_height_attacking": AxisVerdict("identical", "works"),
            "team_shape_inter_line_gap_1_attacking": AxisVerdict("identical", "works"),
            "team_shape_inter_line_gap_2_attacking": AxisVerdict("identical", "works"),
            "team_shape_n_outfield_players_defending": AxisVerdict("identical", "works"),
            "team_shape_centroid_x_defending": AxisVerdict("identical", "works"),
            "team_shape_centroid_y_defending": AxisVerdict("identical", "works"),
            "team_shape_convex_hull_area_defending": AxisVerdict("identical", "works"),
            "team_shape_team_length_defending": AxisVerdict("identical", "works"),
            "team_shape_team_width_defending": AxisVerdict("identical", "works"),
            "team_shape_stretch_index_defending": AxisVerdict("identical", "works"),
            "team_shape_defensive_line_height_defending": AxisVerdict("identical", "works"),
            "team_shape_inter_line_gap_1_defending": AxisVerdict("identical", "works"),
            "team_shape_inter_line_gap_2_defending": AxisVerdict("identical", "works"),
        },
    },
    applicability={
        "team_shape_n_outfield_players_attacking": "no_support",
        "team_shape_centroid_x_attacking": "no_support",
        "team_shape_centroid_y_attacking": "no_support",
        "team_shape_convex_hull_area_attacking": "no_support",
        "team_shape_team_length_attacking": "no_support",
        "team_shape_team_width_attacking": "no_support",
        "team_shape_stretch_index_attacking": "no_support",
        "team_shape_defensive_line_height_attacking": "no_support",
        "team_shape_inter_line_gap_1_attacking": "no_support",
        "team_shape_inter_line_gap_2_attacking": "no_support",
        "team_shape_n_outfield_players_defending": "no_support",
        "team_shape_centroid_x_defending": "no_support",
        "team_shape_centroid_y_defending": "no_support",
        "team_shape_convex_hull_area_defending": "no_support",
        "team_shape_team_length_defending": "no_support",
        "team_shape_team_width_defending": "no_support",
        "team_shape_stretch_index_defending": "no_support",
        "team_shape_defensive_line_height_defending": "no_support",
        "team_shape_inter_line_gap_1_defending": "no_support",
        "team_shape_inter_line_gap_2_defending": "no_support",
    },
    applicability_deltas={
        "team_shape_n_outfield_players_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_centroid_x_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_centroid_y_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_convex_hull_area_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_team_length_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_team_width_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_stretch_index_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_defensive_line_height_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_inter_line_gap_1_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_inter_line_gap_2_attacking": {"extreme": 0.0, "near": 0.0},
        "team_shape_n_outfield_players_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_centroid_x_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_centroid_y_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_convex_hull_area_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_team_length_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_team_width_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_stretch_index_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_defensive_line_height_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_inter_line_gap_1_defending": {"extreme": 0.0, "near": 0.0},
        "team_shape_inter_line_gap_2_defending": {"extreme": 0.0, "near": 0.0},
    },
)
