"""Pins the StatsBomb events converter's coordinate output.

NONE existed before this cycle. `tests/spadl/test_statsbomb.py`'s only two `assert_frame_equal`
calls compare conversions to EACH OTHER (option-invariance), so nothing pinned a coordinate value
and the scalar-affine extraction would have had no gate to refactor under.

Captured on the pre-extraction tree so `_convert_locations` can be proven byte-identical after
`sb_xy_to_spadl` is factored out of it.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from silly_kicks.spadl.statsbomb import _convert_locations

#: Corners, centre, a half-cell offset, and a 3-element SHOT location (x, y, z).
#: The 3-element form takes `y_offset = 0.05` rather than `crc`, which is why row 4's y differs
#: from row 1's despite the same input y -- that branch is EVENT semantics and must not reach the
#: `visible_area` polygon path.
_CASES = [[10.0, 20.0], [60.5, 40.5], [119.0, 79.0], [1.0, 1.0], [60.0, 40.0, 2.5]]


def test_fidelity_1_coordinates_are_pinned():
    """Generated by RUNNING _convert_locations, never hand-derived.

    This has now been got wrong TWICE by hand -- once in the plan draft and once in the first
    draft of this file -- 4 of 5 rows each time, in a test whose entire purpose is pinning
    coordinate values. The arithmetic is a cell-centre shift, a scale, and a y-inversion, and it
    is deceptively easy to reproduce almost-correctly.

    If _CASES changes, REGENERATE by running the function and pasting the output. Do not derive.
    """
    got = _convert_locations(pd.Series(_CASES), 1)
    np.testing.assert_allclose(
        got,
        np.array(
            [
                [8.31250000, 51.42500000],
                [52.50000000, 34.00000000],
                [103.68750000, 1.27500000],
                [0.43750000, 67.57500000],
                [52.06250000, 34.04250000],
            ]
        ),
        rtol=0,
        # atol CHOSEN, not inherited (CLAUDE.md/ADR-050): this is a COMMITTED artifact compared in
        # CI across ubuntu and windows, the same shape as the feature contract. 1e-6 m is a
        # micrometre -- orders of magnitude below any real coordinate change, and above the float
        # noise these values actually carry (e.g. 1.2750000000000057, 0.8924999999999983), which is
        # what a tighter atol against 4-dp literals trips on.
        atol=1e-6,
    )


def test_fidelity_2_coordinates_are_pinned():
    """The higher-granularity branch: cell side 0.1 rather than 1.0, so crc is 0.05."""
    got = _convert_locations(pd.Series(_CASES), 2)
    np.testing.assert_allclose(
        got,
        np.array(
            [
                [8.70625000, 51.04250000],
                [52.89375000, 33.61750000],
                [104.08125000, 0.89250000],
                [0.83125000, 67.19250000],
                [52.45625000, 34.04250000],
            ]
        ),
        rtol=0,
        # atol CHOSEN, not inherited (CLAUDE.md/ADR-050): this is a COMMITTED artifact compared in
        # CI across ubuntu and windows, the same shape as the feature contract. 1e-6 m is a
        # micrometre -- orders of magnitude below any real coordinate change, and above the float
        # noise these values actually carry (e.g. 1.2750000000000057, 0.8924999999999983), which is
        # what a tighter atol against 4-dp literals trips on.
        atol=1e-6,
    )


def test_the_two_fidelities_actually_differ():
    """Non-vacuity: if the fidelity branch were dead, both blocks above would pin the same
    numbers and the refactor could break one without failing either."""
    f1 = _convert_locations(pd.Series(_CASES), 1)
    f2 = _convert_locations(pd.Series(_CASES), 2)
    assert not np.allclose(f1, f2), "the xy_fidelity_version branch is not exercised"


def test_the_clip_is_reachable_on_events():
    """The clip is EVENT semantics and must survive the extraction of the unclipped affine.

    A vertex outside the pitch is clamped here. `visible_area` must NOT inherit this -- a camera
    legitimately sees past the touchline (ADR-038's defect class) -- which is why the affine and
    the clip are separated rather than promoted together.
    """
    got = _convert_locations(pd.Series([[-40.0, -40.0]]), 1)
    assert got[0, 0] == 0.0, "x below the pitch should clamp to 0.0"
    assert got[0, 1] == 68.0, "y above the pitch should clamp to the far touchline"
