"""silly_kicks.tracking --- tracking-data namespace.

PR-S19 (silly-kicks 2.7.0) shipped the primitive layer: schema, per-provider
adapters, and the link_actions_to_frames primitive. PR-S20 (silly-kicks 2.8.0,
ADR-005) shipped the first tracking-aware feature set (action_context: 4
features + aggregator + lift_to_states extension utility) on top of those
primitives. PR-S21 (silly-kicks 2.9.0) shipped pre_shot_gk_position_*. PR-S24
(silly-kicks 3.1.0) ships TF-6 sync_score, TF-8 smoothing/velocity, TF-9
interpolation, TF-12 pre_shot_gk_angle_* + the shared `preprocess` module.
PR-S27 ships TF-13 defending_gk_from_frames + TF-14 compute_defensive_line +
6 per-Series action-coupled features + add_defensive_line + defensive_line_xfns.
PR-S31 ships TF-7 pitch_control subpackage (Spearman/Fernandez-Bornn/Voronoi) +
action-coupled VAEP integration (pitch_control_at_target + add_pitch_control +
pitch_control_xfns factory). PR-S33 ships TF-31 team shape envelope
(compute_team_shape + add_team_shape + team_shape_xfns) + TF-32 Ward-clustering
line-breaking (detect_line_breaking + add_line_break method="ward" dispatch +
line_breaking_ward_xfns).
"""

__all__ = [
    "DAS_SOURCE_COMPUTED",
    "DAS_SOURCE_TEAM_UNRESOLVED",
    "DAS_SOURCE_UNLINKED",
    "DAS_SOURCE_UNSCOREABLE_CALL",
    "DAS_SOURCE_UNSCOREABLE_FRAME",
    "DAS_SOURCE_VALUES",
    "DEFENSIVE_CREDIT_RULES",
    "FOV_REGIME_VALUES",
    "GHOST_GK_COMPUTED",
    "GHOST_GK_DIRECTION_UNRESOLVED",
    "GHOST_GK_GOAL_END_UNRESOLVED",
    "GHOST_GK_NO_KEEPER",
    "GHOST_GK_SOURCE_VALUES",
    "GHOST_GK_UNLINKED",
    "GHOST_GK_VELOCITY_UNAVAILABLE",
    "GRADIENTSPORTS_TRACKING_FRAMES_COLUMNS",
    "KEEPER_ID_SOURCE_DERIVED",
    "KEEPER_ID_SOURCE_EVENT",
    "KEEPER_ID_SOURCE_NATIVE",
    "KEEPER_ID_SOURCE_ROSTER",
    "KEEPER_ID_SOURCE_UNRESOLVED",
    "KEEPER_ID_SOURCE_VALUES",
    "KLOPPY_TRACKING_FRAMES_COLUMNS",
    "METRICA_TRACKING_FRAMES_COLUMNS",
    "REGION_OBSERVATION_DEGENERATE_REGION",
    "REGION_OBSERVATION_SOURCE_VALUES",
    "SKILLCORNER_TRACKING_FRAMES_COLUMNS",
    "SPEED_SOURCE_UNAVAILABLE",
    "SPORTEC_TRACKING_FRAMES_COLUMNS",
    "TRACKING_CATEGORICAL_DOMAINS",
    "TRACKING_CONSTRAINTS",
    "TRACKING_FRAMES_COLUMNS",
    "VELOCITY_REGIME_VALUES",
    "VISIBLE_AREA_DEGENERATE_POLYGON",
    "VISIBLE_AREA_NO_POLYGON",
    "VISIBLE_AREA_OBSERVED",
    "VISIBLE_AREA_SOURCE_VALUES",
    "VISIBLE_AREA_UNLINKED",
    "ActionFrameContext",
    "AndrienkoParams",
    "BekkersParams",
    "CoverShadowParams",
    "DasUnscoreableError",
    "DefensiveCreditParams",
    "ElasticSyncParams",
    "FernandezBornnParams",
    "FovDiagnosis",
    "GhostClampWarning",
    "GhostGkDensity",
    "GhostGkModel",
    "GhostGkVariant",
    "GkCompletionModel",
    "GoalEndUnresolvedError",
    "GoalMap",
    "GradientsportsRosterReport",
    "IdDtypeDiagnosis",
    "IgnoredSurfaceInputsWarning",
    "KeeperIdentity",
    "KeeperIdentityMap",
    "KeeperIdentityReport",
    "LaneControlResult",
    "LineBreakingParams",
    "LinkParams",
    "LinkReport",
    "Method",
    "MissingFeatureContractWarning",
    "ObsoParams",
    "ObsoSurface",
    "OrientationUnresolvedWarning",
    "PackingParams",
    "PitchControlSurface",
    "PlayerInfluence",
    "PositionLabel",
    "PreprocessConfig",
    "PressureParams",
    "ReceiverModel",
    "RestartCoordinateReport",
    "RunValuationParams",
    "RunValueCoverageWarning",
    "ShapeGraph",
    "ShotGoalmouthParams",
    "ShotGoalmouthReport",
    "SpaceCreationParams",
    "SpearmanParams",
    "StructuralPassParams",
    "SyntheticEPVWarning",
    "TimeBaseDiagnosis",
    "TrackingConversionReport",
    "TrackingFeaturesReport",
    "UnverifiableFeatureContractWarning",
    "VelocityRegimeDiagnosis",
    "VoronoiParams",
    "XCrossAttemptModel",
    "XCrossFeatureSet",
    "XShotFeatureSet",
    "XShotOccurrenceModel",
    "XtGkParams",
    "XtGkReport",
    "acting_gk_from_frames",
    "actor_arc_length_pre_window",
    "actor_displacement_pre_window",
    "actor_pre_window_default_xfns",
    "actor_reachable_area_m2",
    "actor_speed",
    "add_action_context",
    "add_actor_pre_window",
    "add_cover_shadows",
    "add_das",
    "add_defending_gk_player_id",
    "add_defensive_credit",
    "add_defensive_line",
    "add_elastic_sync",
    "add_ghost_gk",
    "add_gk_completion",
    "add_gk_influence",
    "add_gradientsports_player_ids",
    "add_line_break",
    "add_obso",
    "add_off_ball_context",
    "add_off_ball_run_values",
    "add_off_ball_runs",
    "add_packing",
    "add_pausa",
    "add_pitch_control",
    "add_player_influence",
    "add_pre_shot_gk_angle",
    "add_pre_shot_gk_position",
    "add_press_commitment",
    "add_pressure_on_actor",
    "add_shape_graph",
    "add_shot_goalmouth",
    "add_space_creation",
    "add_structural_pass",
    "add_sync_score",
    "add_team_shape",
    "add_visible_area_coverage",
    "add_xcross_attempt",
    "add_xshot_occurrence",
    "add_xt_gk",
    "align_events_to_frames",
    "apply_keeper_identities_to_frames",
    "back_line_high_x",
    "back_n_count",
    "ball_carrier_at_action",
    "classify_region_observation",
    "compactness_x",
    "compute_blocking_score",
    "compute_bravery",
    "compute_defensive_credits",
    "compute_defensive_line",
    "compute_ghost_gk",
    "compute_gk_completion",
    "compute_obso_surface",
    "compute_packing_metrics",
    "compute_pass_obso",
    "compute_pausa",
    "compute_pausa_batch",
    "compute_pitch_control",
    "compute_pitch_control_at_points",
    "compute_player_influence",
    "compute_shape_graph",
    "compute_shot_goalmouth",
    "compute_space_created",
    "compute_structural_pass_metrics",
    "compute_team_shape",
    "compute_threat_pc",
    "compute_tti",
    "compute_xcross_attempt",
    "compute_xshot_occurrence",
    "compute_xt_gk",
    "cover_shadow_xfns",
    "das_at_action",
    "das_xfns",
    "defenders_in_triangle_to_goal",
    "defending_gk_from_frames",
    "defensive_line_x",
    "defensive_line_xfns",
    "derive_team_in_possession",
    "derive_velocities",
    "detect_line_breaking",
    "detect_off_ball_runs",
    "elastic_sync_xfns",
    "extract_ball_features",
    "extract_xcross_features",
    "extract_xshot_features",
    "feature_framework",
    "features",
    "filter_extratime_frames",
    "get_das",
    "get_individual_das",
    "get_provider_defaults",
    "get_xc",
    "ghost_gk_xfns",
    "gk_closing_time_mean_s",
    "gk_closing_time_min_s",
    "gk_distribution_mask",
    "gk_influence_xfns",
    "gk_pitch_control_share_weighted",
    "gk_reachable_area_m2",
    "gradientsports",
    "infer_ball_carrier",
    "infer_positions",
    "intended_receiver_positions",
    "interpolate_frames",
    "kloppy",
    "lane_control",
    "lateral_width",
    "lift_to_states",
    "line_breaking_ward_xfns",
    "link_actions_to_frames",
    "max_lateral_gap",
    "metrica",
    "nearest_defender_distance",
    "obso_actual",
    "obso_optimal",
    "obso_peak",
    "obso_xfns",
    "off_ball_context_xfns",
    "off_ball_run_value_xfns",
    "off_ball_xt_opponent",
    "off_ball_xt_team",
    "orient_frames_to_ltr",
    "orient_frames_to_ltr_by_geometry",
    "packing_xfns",
    "pausa_xfns",
    "pitch_control",
    "pitch_control_at_target",
    "pitch_control_default_xfns",
    "pitch_control_xfns",
    "play_left_to_right",
    "player_influence_xfns",
    "point_observed",
    "pre_shot_gk_angle_default_xfns",
    "pre_shot_gk_angle_off_goal_line",
    "pre_shot_gk_angle_to_shot_trajectory",
    "pre_shot_gk_default_xfns",
    "pre_shot_gk_distance_to_goal",
    "pre_shot_gk_distance_to_shot",
    "pre_shot_gk_full_default_xfns",
    "pre_shot_gk_x",
    "pre_shot_gk_y",
    "prepare_ghost_gk_training_data",
    "prepare_xcross_training_data",
    "prepare_xshot_training_data",
    "preprocess",
    "pressure_default_xfns",
    "pressure_on_actor",
    "reachable_area_opponent",
    "reachable_area_team",
    "receiver_zone_density",
    "region_observed_fraction",
    "require_et_direction",
    "resolve_defended_goals",
    "resolve_gk_geometry",
    "resolve_intended_receiver",
    "resolve_keeper_identities",
    "resolve_restart_geometry",
    "run_tracking_features",
    "schema",
    "secured_reception",
    "select_back_line_players",
    "serve_ghost_gk_positions",
    "shape_graph_xfns",
    "shot_crossing_y",
    "shot_crossing_z",
    "shot_on_target_derived",
    "shot_speed",
    "shot_time_to_goal_line",
    "skillcorner",
    "slice_around_event",
    "smooth_frames",
    "snapshot_to_tracking_frames",
    "space_creation_xfns",
    "sportec",
    "structural_pass_xfns",
    "subsample_negatives",
    "sync_score",
    "team_shape_xfns",
    "tracking_default_xfns",
    "utils",
    "validate_fov",
    "validate_id_dtypes",
    "validate_time_base",
    "validate_velocity_regime",
    "value_off_ball_runs",
    "xcross_attempt_xfns",
    "xshot_occurrence_xfns",
    "xt_gk_xfns",
]

from . import (
    feature_framework,
    features,
    gradientsports,
    metrica,
    pitch_control,
    preprocess,
    schema,
    skillcorner,
    sportec,
    utils,
)
from ._ball_carrier import derive_team_in_possession, infer_ball_carrier
from ._cover_shadows import (
    CoverShadowParams,
    LaneControlResult,
    compute_blocking_score,
    compute_threat_pc,
    lane_control,
)
from ._das import (
    DAS_SOURCE_COMPUTED,
    DAS_SOURCE_TEAM_UNRESOLVED,
    DAS_SOURCE_UNLINKED,
    DAS_SOURCE_UNSCOREABLE_CALL,
    DAS_SOURCE_UNSCOREABLE_FRAME,
    DAS_SOURCE_VALUES,
    DasUnscoreableError,
    get_das,
    get_individual_das,
    get_xc,
)
from ._defensive_line import compute_defensive_line, select_back_line_players
from ._elastic_sync import ElasticSyncParams, align_events_to_frames, extract_ball_features
from ._ghost_gk import (
    GHOST_GK_COMPUTED,
    GHOST_GK_DIRECTION_UNRESOLVED,
    GHOST_GK_GOAL_END_UNRESOLVED,
    GHOST_GK_NO_KEEPER,
    GHOST_GK_SOURCE_VALUES,
    GHOST_GK_UNLINKED,
    GHOST_GK_VELOCITY_UNAVAILABLE,
    GhostClampWarning,
    GhostGkDensity,
    GhostGkModel,
    GhostGkVariant,
    compute_ghost_gk,
    prepare_ghost_gk_training_data,
    serve_ghost_gk_positions,
)
from ._gk_completion import GkCompletionModel, compute_gk_completion
from ._gk_geometry import resolve_gk_geometry, resolve_restart_geometry
from ._line_breaking import LineBreakingParams, detect_line_breaking
from ._obso import ObsoParams, ObsoSurface, compute_obso_surface, compute_pass_obso
from ._packing import PackingParams, compute_packing_metrics, secured_reception
from ._pausa import compute_pausa, compute_pausa_batch
from ._player_influence import PlayerInfluence, compute_player_influence
from ._receiver import (
    ReceiverModel,
    intended_receiver_positions,
    resolve_intended_receiver,
)
from ._restart_report import RestartCoordinateReport
from ._run_features import TrackingFeaturesReport, run_tracking_features
from ._run_values import RunValuationParams, detect_off_ball_runs, value_off_ball_runs
from ._shape_graph import PositionLabel, ShapeGraph, compute_shape_graph, infer_positions
from ._shot_goalmouth import ShotGoalmouthParams, ShotGoalmouthReport, compute_shot_goalmouth
from ._snapshot import snapshot_to_tracking_frames
from ._space_creation import SpaceCreationParams, compute_space_created
from ._structural_pass import StructuralPassParams, compute_structural_pass_metrics
from ._team_shape import compute_team_shape
from ._visibility import (
    REGION_OBSERVATION_DEGENERATE_REGION,
    REGION_OBSERVATION_SOURCE_VALUES,
    VISIBLE_AREA_DEGENERATE_POLYGON,
    VISIBLE_AREA_NO_POLYGON,
    VISIBLE_AREA_OBSERVED,
    VISIBLE_AREA_SOURCE_VALUES,
    VISIBLE_AREA_UNLINKED,
    add_visible_area_coverage,
    classify_region_observation,
    point_observed,
    region_observed_fraction,
)
from ._warnings import (
    IgnoredSurfaceInputsWarning,
    MissingFeatureContractWarning,
    OrientationUnresolvedWarning,
    RunValueCoverageWarning,
    SyntheticEPVWarning,
    UnverifiableFeatureContractWarning,
)
from ._xcross_attempt import (
    XCrossAttemptModel,
    XCrossFeatureSet,
    add_xcross_attempt,
    compute_xcross_attempt,
    extract_xcross_features,
    prepare_xcross_training_data,
    xcross_attempt_xfns,
)
from ._xshot_occurrence import (
    XShotFeatureSet,
    XShotOccurrenceModel,
    add_xshot_occurrence,
    compute_xshot_occurrence,
    extract_xshot_features,
    prepare_xshot_training_data,
    subsample_negatives,
    xshot_occurrence_xfns,
)
from ._xt_gk import XtGkParams, XtGkReport, compute_xt_gk
from .defensive_credit import (
    DEFENSIVE_CREDIT_RULES,
    DefensiveCreditParams,
    compute_bravery,
    compute_defensive_credits,
)
from .direction import orient_frames_to_ltr_by_geometry, require_et_direction
from .feature_framework import ActionFrameContext, lift_to_states
from .features import (
    KEEPER_ID_SOURCE_DERIVED,
    KEEPER_ID_SOURCE_EVENT,
    KEEPER_ID_SOURCE_NATIVE,
    KEEPER_ID_SOURCE_ROSTER,
    KEEPER_ID_SOURCE_UNRESOLVED,
    KEEPER_ID_SOURCE_VALUES,
    GoalEndUnresolvedError,
    GoalMap,
    KeeperIdentity,
    KeeperIdentityMap,
    KeeperIdentityReport,
    acting_gk_from_frames,
    actor_arc_length_pre_window,
    actor_displacement_pre_window,
    actor_pre_window_default_xfns,
    actor_reachable_area_m2,
    actor_speed,
    add_action_context,
    add_actor_pre_window,
    add_cover_shadows,
    add_das,
    add_defending_gk_player_id,
    add_defensive_credit,
    add_defensive_line,
    add_elastic_sync,
    add_ghost_gk,
    add_gk_completion,
    add_gk_influence,
    add_line_break,
    add_obso,
    add_off_ball_context,
    add_off_ball_run_values,
    add_off_ball_runs,
    add_packing,
    add_pausa,
    add_pitch_control,
    add_player_influence,
    add_pre_shot_gk_angle,
    add_pre_shot_gk_position,
    add_press_commitment,
    add_pressure_on_actor,
    add_shape_graph,
    add_shot_goalmouth,
    add_space_creation,
    add_structural_pass,
    add_team_shape,
    add_xt_gk,
    apply_keeper_identities_to_frames,
    back_line_high_x,
    back_n_count,
    ball_carrier_at_action,
    compactness_x,
    cover_shadow_xfns,
    das_at_action,
    das_xfns,
    defenders_in_triangle_to_goal,
    defending_gk_from_frames,
    defensive_line_x,
    defensive_line_xfns,
    elastic_sync_xfns,
    ghost_gk_xfns,
    gk_closing_time_mean_s,
    gk_closing_time_min_s,
    gk_distribution_mask,
    gk_influence_xfns,
    gk_pitch_control_share_weighted,
    gk_reachable_area_m2,
    lateral_width,
    line_breaking_ward_xfns,
    max_lateral_gap,
    nearest_defender_distance,
    obso_actual,
    obso_optimal,
    obso_peak,
    obso_xfns,
    off_ball_context_xfns,
    off_ball_run_value_xfns,
    off_ball_xt_opponent,
    off_ball_xt_team,
    packing_xfns,
    pausa_xfns,
    pitch_control_at_target,
    pitch_control_default_xfns,
    pitch_control_xfns,
    player_influence_xfns,
    pre_shot_gk_angle_default_xfns,
    pre_shot_gk_angle_off_goal_line,
    pre_shot_gk_angle_to_shot_trajectory,
    pre_shot_gk_default_xfns,
    pre_shot_gk_distance_to_goal,
    pre_shot_gk_distance_to_shot,
    pre_shot_gk_full_default_xfns,
    pre_shot_gk_x,
    pre_shot_gk_y,
    pressure_default_xfns,
    pressure_on_actor,
    reachable_area_opponent,
    reachable_area_team,
    receiver_zone_density,
    resolve_defended_goals,
    resolve_keeper_identities,
    shape_graph_xfns,
    shot_crossing_y,
    shot_crossing_z,
    shot_on_target_derived,
    shot_speed,
    shot_time_to_goal_line,
    space_creation_xfns,
    structural_pass_xfns,
    team_shape_xfns,
    tracking_default_xfns,
    xt_gk_xfns,
)
from .gradientsports import GradientsportsRosterReport, add_gradientsports_player_ids
from .pitch_control import (
    FernandezBornnParams,
    PitchControlSurface,
    SpearmanParams,
    VoronoiParams,
    compute_pitch_control,
    compute_pitch_control_at_points,
    compute_tti,
)
from .preprocess import (
    PreprocessConfig,
    derive_velocities,
    get_provider_defaults,
    interpolate_frames,
    smooth_frames,
)
from .pressure import (
    AndrienkoParams,
    BekkersParams,
    LinkParams,
    Method,
    PressureParams,
)
from .schema import (
    FOV_REGIME_VALUES,
    GRADIENTSPORTS_TRACKING_FRAMES_COLUMNS,
    KLOPPY_TRACKING_FRAMES_COLUMNS,
    METRICA_TRACKING_FRAMES_COLUMNS,
    SKILLCORNER_TRACKING_FRAMES_COLUMNS,
    SPEED_SOURCE_UNAVAILABLE,
    SPORTEC_TRACKING_FRAMES_COLUMNS,
    TRACKING_CATEGORICAL_DOMAINS,
    TRACKING_CONSTRAINTS,
    TRACKING_FRAMES_COLUMNS,
    VELOCITY_REGIME_VALUES,
    FovDiagnosis,
    IdDtypeDiagnosis,
    LinkReport,
    TimeBaseDiagnosis,
    TrackingConversionReport,
    VelocityRegimeDiagnosis,
)
from .utils import (
    add_sync_score,
    filter_extratime_frames,
    link_actions_to_frames,
    orient_frames_to_ltr,
    play_left_to_right,
    slice_around_event,
    sync_score,
    validate_fov,
    validate_id_dtypes,
    validate_time_base,
    validate_velocity_regime,
)

try:
    from . import kloppy
except ImportError:
    pass
