"""Implements the feature tranformers of the VAEP framework."""

import numpy as np
import pandas as pd

import silly_kicks.atomic.spadl.config as atomicspadl
from silly_kicks.vaep.features.bodypart import (
    bodypart,
    bodypart_detailed,
    bodypart_detailed_onehot,
    bodypart_onehot,
)
from silly_kicks.vaep.features.context import player_possession_time, team
from silly_kicks.vaep.features.core import (
    Actions,
    Features,
    FeatureTransfomer,
    GameStates,
    _actiontype,
    gamestates,
    simple,
)
from silly_kicks.vaep.features.temporal import speed, time, time_delta

__all__ = [
    "actiontype",
    "actiontype_onehot",
    "bodypart",
    "bodypart_detailed",
    "bodypart_detailed_onehot",
    "bodypart_onehot",
    "direction",
    "feature_column_names",
    "gamestates",
    "goalscore",
    "location",
    "movement_polar",
    "play_left_to_right",
    "player_possession_time",
    "polar",
    "speed",
    "team",
    "time",
    "time_delta",
]


@simple
def actiontype(actions: Actions) -> Features:
    """Actiontype feature using atomic SPADL config (33 action types).

    Examples
    --------
    Extract the atomic action-type integer feature per gamestate slot::

        from silly_kicks.atomic.vaep.features import actiontype, gamestates

        states = gamestates(atomic, nb_prev_actions=3)
        feats = actiontype(states)
        # feats has columns 'type_id_a0', 'type_id_a1', 'type_id_a2'.
    """
    return _actiontype(actions, _spadl_cfg=atomicspadl)


def feature_column_names(fs: list[FeatureTransfomer], nb_prev_actions: int = 3) -> list[str]:
    """Return the names of the features generated by a list of transformers.

    Parameters
    ----------
    fs : list(callable)
        A list of feature transformers.
    nb_prev_actions : int, default=3  # noqa: DAR103
        The number of previous actions included in the game state.

    Returns
    -------
    list(str)
        The name of each generated feature.

    Examples
    --------
    Enumerate the column names a feature stack will produce, without
    actually computing features on real data::

        from silly_kicks.atomic.vaep.features import (
            actiontype_onehot, location, feature_column_names,
        )

        names = feature_column_names([actiontype_onehot, location], nb_prev_actions=3)
        # names is e.g. ['actiontype_pass_a0', ..., 'x_a0', 'y_a0', ...].
    """
    spadlcolumns = [
        "game_id",
        "original_event_id",
        "action_id",
        "period_id",
        "time_seconds",
        "team_id",
        "player_id",
        "x",
        "y",
        "dx",
        "dy",
        "bodypart_id",
        "bodypart_name",
        "type_id",
        "type_name",
    ]
    dummy_actions = pd.DataFrame(np.zeros((10, len(spadlcolumns))), columns=spadlcolumns)
    for c in spadlcolumns:
        if "name" in c:
            dummy_actions[c] = dummy_actions[c].astype(str)
    gs = gamestates(dummy_actions, nb_prev_actions)  # type: ignore
    return list(pd.concat([f(gs) for f in fs], axis=1).columns)


def play_left_to_right(gamestates: GameStates, home_team_id: int) -> GameStates:
    """Perform all action in the same playing direction.

    This changes the start and end location of each action, such that all actions
    are performed as if the team plays from left to right.

    Parameters
    ----------
    gamestates : GameStates
        The game states of a game.
    home_team_id : int
        The ID of the home team.

    Returns
    -------
    list(pd.DataFrame)
        The game states with all actions performed left to right.

    Examples
    --------
    Mirror gamestates so all actions are performed left-to-right (per home team)::

        from silly_kicks.atomic.vaep.features import gamestates, play_left_to_right

        states = gamestates(atomic, nb_prev_actions=3)
        states = play_left_to_right(states, home_team_id=100)
        # All away-team rows in each slot now have flipped (x, y) and (dx, dy).
    """
    a0 = gamestates[0]
    away_idx = a0.team_id != home_team_id
    for actions in gamestates:
        actions.loc[away_idx, "x"] = atomicspadl.field_length - actions[away_idx]["x"].values  # type: ignore[reportAttributeAccessIssue]
        actions.loc[away_idx, "y"] = atomicspadl.field_width - actions[away_idx]["y"].values  # type: ignore[reportAttributeAccessIssue]
        actions.loc[away_idx, "dx"] = -actions[away_idx]["dx"].values  # type: ignore[reportAttributeAccessIssue]
        actions.loc[away_idx, "dy"] = -actions[away_idx]["dy"].values  # type: ignore[reportAttributeAccessIssue]
    return gamestates


@simple
def actiontype_onehot(actions: Actions) -> Features:
    """Get the one-hot-encoded type of each action.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        A one-hot encoding of each action's type.

    Examples
    --------
    One-hot encode atomic action types per gamestate slot::

        from silly_kicks.atomic.vaep.features import actiontype_onehot, gamestates

        states = gamestates(atomic, nb_prev_actions=3)
        feats = actiontype_onehot(states)
        # feats has 33 boolean columns per slot (one per atomic action type).
    """
    X = {}
    for type_id, type_name in enumerate(atomicspadl.actiontypes):
        col = "actiontype_" + type_name
        X[col] = actions["type_id"] == type_id
    return pd.DataFrame(X, index=actions.index)


@simple
def location(actions: Actions) -> Features:
    """Get the location where each action started.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        The 'x' and 'y' location of each action.

    Examples
    --------
    Extract atomic location features per gamestate slot::

        from silly_kicks.atomic.vaep.features import gamestates, location

        states = gamestates(atomic, nb_prev_actions=3)
        feats = location(states)
        # feats has columns 'x_a0', 'y_a0', 'x_a1', 'y_a1', 'x_a2', 'y_a2'.
    """
    return actions[["x", "y"]]  # type: ignore[reportReturnType]


_goal_x = atomicspadl.field_length
_goal_y = atomicspadl.field_width / 2


@simple
def polar(actions: Actions) -> Features:
    """Get the polar coordinates of each action's start location.

    The center of the opponent's goal is used as the origin.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        The 'dist_to_goal' and 'angle_to_goal' of each action.

    Examples
    --------
    Compute polar features (distance + angle to opponent goal) per slot::

        from silly_kicks.atomic.vaep.features import gamestates, polar

        states = gamestates(atomic, nb_prev_actions=3)
        feats = polar(states)
        # feats has columns 'dist_to_goal_a0', 'angle_to_goal_a0', etc.
    """
    polardf = pd.DataFrame(index=actions.index)
    dx = (_goal_x - actions["x"]).abs().to_numpy()
    dy = (_goal_y - actions["y"]).abs().to_numpy()
    polardf["dist_to_goal"] = np.sqrt(dx**2 + dy**2)
    with np.errstate(divide="ignore", invalid="ignore"):
        polardf["angle_to_goal"] = np.nan_to_num(np.arctan(dy / dx))
    return polardf


@simple
def movement_polar(actions: Actions) -> Features:
    """Get the distance covered and direction of each action.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        The distance covered ('mov_d') and direction ('mov_angle') of each action.

    Examples
    --------
    Compute per-action movement magnitude + angle features per slot::

        from silly_kicks.atomic.vaep.features import gamestates, movement_polar

        states = gamestates(atomic, nb_prev_actions=3)
        feats = movement_polar(states)
        # feats has 'mov_d_a0' (metres) and 'mov_angle_a0' (radians) per slot.
    """
    mov = pd.DataFrame(index=actions.index)
    mov["mov_d"] = np.sqrt(actions.dx**2 + actions.dy**2)
    with np.errstate(divide="ignore", invalid="ignore"):
        mov["mov_angle"] = np.arctan2(actions.dy, actions.dx)
        mov.loc[actions.dy == 0, "mov_angle"] = 0  # fix float errors
    return mov


@simple
def direction(actions: Actions) -> Features:
    """Get the direction of the action as components of the unit vector.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        The x-component ('dx') and y-compoment ('mov_angle') of the unit
        vector of each action.

    Examples
    --------
    Compute per-action unit-direction vector features per slot::

        from silly_kicks.atomic.vaep.features import direction, gamestates

        states = gamestates(atomic, nb_prev_actions=3)
        feats = direction(states)
        # feats has 'dx_a0' and 'dy_a0' (unit-length components, 0 if static).
    """
    mov = pd.DataFrame(index=actions.index)
    totald = np.sqrt(actions.dx**2 + actions.dy**2)
    for d in ["dx", "dy"]:
        # we don't want to give away the end location,
        # just the direction of the ball
        # We also don't want to divide by zero
        mov[d] = actions[d].mask(totald > 0, actions[d] / totald)

    return mov


def goalscore(gamestates: GameStates) -> Features:
    """Get the number of goals scored by each team after the action.

    Parameters
    ----------
    gamestates : GameStates
        The gamestates of a game.

    Returns
    -------
    Features
        The number of goals scored by the team performing the last action of the
        game state ('goalscore_team'), by the opponent ('goalscore_opponent'),
        and the goal difference between both teams ('goalscore_diff').

    Examples
    --------
    Compute the cumulative-goalscore context feature on a gamestate sequence::

        from silly_kicks.atomic.vaep.features import gamestates, goalscore

        states = gamestates(atomic, nb_prev_actions=3)
        feats = goalscore(states)
        # feats has 'goalscore_team', 'goalscore_opponent', 'goalscore_diff'.
    """
    actions = gamestates[0]
    teamA = actions["team_id"].values[0]
    goals = actions.type_name == "goal"
    owngoals = actions["type_name"].str.contains("owngoal")

    teamisA = actions["team_id"] == teamA
    teamisB = ~teamisA
    goalsteamA = (goals & teamisA) | (owngoals & teamisB)
    goalsteamB = (goals & teamisB) | (owngoals & teamisA)
    goalscoreteamA = goalsteamA.cumsum() - goalsteamA
    goalscoreteamB = goalsteamB.cumsum() - goalsteamB

    scoredf = pd.DataFrame(index=actions.index)
    scoredf["goalscore_team"] = (goalscoreteamA * teamisA) + (goalscoreteamB * teamisB)
    scoredf["goalscore_opponent"] = (goalscoreteamB * teamisA) + (goalscoreteamA * teamisB)
    scoredf["goalscore_diff"] = scoredf["goalscore_team"] - scoredf["goalscore_opponent"]
    return scoredf
