"""Implements the feature tranformers of the VAEP framework."""

import numpy as np
import pandas as pd
from sklearn.exceptions import NotFittedError

import silly_kicks.atomic.spadl.config as atomicspadl
import silly_kicks.spadl.config as stdspadl
from silly_kicks.vaep.feature_framework import (
    Actions,
    Features,
    FeatureTransfomer,
    GameStates,
    actiontype_categorical,
    gamestates,
    simple,
)
from silly_kicks.vaep.features.bodypart import (
    bodypart,
    bodypart_detailed,
    bodypart_detailed_onehot,
    bodypart_onehot,
)
from silly_kicks.vaep.features.context import player_possession_time, team
from silly_kicks.vaep.features.temporal import speed, time, time_delta

__all__ = [
    "actiontype",
    "actiontype_onehot",
    "bodypart",
    "bodypart_detailed",
    "bodypart_detailed_onehot",
    "bodypart_onehot",
    "direction",
    "feature_column_names",
    "gamestates",
    "goalscore",
    "location",
    "movement_polar",
    "play_left_to_right",
    "player_possession_time",
    "polar",
    "speed",
    "team",
    "time",
    "time_delta",
    "xt_xfns",
]


@simple
def actiontype(actions: Actions) -> Features:
    """Actiontype feature using atomic SPADL config (33 action types).

    Examples
    --------
    Extract the atomic action-type integer feature per gamestate slot::

        from silly_kicks.atomic.vaep.features import actiontype, gamestates

        states = gamestates(atomic, nb_prev_actions=3)
        feats = actiontype(states)
        # feats has columns 'type_id_a0', 'type_id_a1', 'type_id_a2'.
    """
    return actiontype_categorical(actions, atomicspadl)


def feature_column_names(fs: list[FeatureTransfomer], nb_prev_actions: int = 3) -> list[str]:
    """Return the names of the features generated by a list of transformers.

    Parameters
    ----------
    fs : list(callable)
        A list of feature transformers.
    nb_prev_actions : int, default=3  # noqa: DAR103
        The number of previous actions included in the game state.

    Returns
    -------
    list(str)
        The name of each generated feature.

    Examples
    --------
    Enumerate the column names a feature stack will produce, without
    actually computing features on real data::

        from silly_kicks.atomic.vaep.features import (
            actiontype_onehot, location, feature_column_names,
        )

        names = feature_column_names([actiontype_onehot, location], nb_prev_actions=3)
        # names is e.g. ['actiontype_pass_a0', ..., 'x_a0', 'y_a0', ...].
    """
    spadlcolumns = [
        "game_id",
        "original_event_id",
        "action_id",
        "period_id",
        "time_seconds",
        "team_id",
        "player_id",
        "x",
        "y",
        "dx",
        "dy",
        "bodypart_id",
        "bodypart_name",
        "type_id",
        "type_name",
    ]
    dummy_actions = pd.DataFrame(np.zeros((10, len(spadlcolumns))), columns=spadlcolumns)
    for c in spadlcolumns:
        if "name" in c:
            dummy_actions[c] = dummy_actions[c].astype(str)
    gs = gamestates(dummy_actions, nb_prev_actions)  # type: ignore
    return list(pd.concat([f(gs) for f in fs], axis=1).columns)


def play_left_to_right(gamestates: GameStates, home_team_id: int) -> GameStates:
    """Mirror away-team atomic gamestate rows from absolute-frame to SPADL LTR.

    Public boundary helper for callers who have absolute-frame-home-right
    atomic gamestates and want to convert them to canonical SPADL LTR
    convention. Mirrors ``(x, y)`` and negates ``(dx, dy)`` for every row whose
    ``a0.team_id != home_team_id``.

    .. versionchanged:: 3.0.0
        Pre-3.0.0, ``vaep.base.VAEP.compute_features`` (inherited by
        ``AtomicVAEP``) called this function unconditionally on every input.
        ADR-006 / PR-S22 removed that internal call because every silly-kicks
        3.0.0+ converter outputs canonical SPADL LTR by default. This function
        is retained as a public utility for external callers.

    Parameters
    ----------
    gamestates : GameStates
        Atomic gamestates in absolute-frame-home-right convention.
    home_team_id : int
        ID of the home team.

    Returns
    -------
    GameStates
        Atomic gamestates with all rows performed left-to-right.

    Examples
    --------
    Convert externally-loaded absolute-frame atomic gamestates to SPADL LTR::

        from silly_kicks.atomic.vaep.features import gamestates, play_left_to_right

        states = gamestates(atomic, nb_prev_actions=3)
        ltr_states = play_left_to_right(states, home_team_id=100)
        # All away-team rows in each slot now have flipped (x, y) and negated (dx, dy).
    """
    a0 = gamestates[0]
    away_idx = a0.team_id != home_team_id
    for actions in gamestates:
        actions.loc[away_idx, "x"] = atomicspadl.field_length - actions[away_idx]["x"].values  # type: ignore[reportAttributeAccessIssue]
        actions.loc[away_idx, "y"] = atomicspadl.field_width - actions[away_idx]["y"].values  # type: ignore[reportAttributeAccessIssue]
        actions.loc[away_idx, "dx"] = -actions[away_idx]["dx"].values  # type: ignore[reportAttributeAccessIssue]
        actions.loc[away_idx, "dy"] = -actions[away_idx]["dy"].values  # type: ignore[reportAttributeAccessIssue]
    return gamestates


@simple
def actiontype_onehot(actions: Actions) -> Features:
    """Get the one-hot-encoded type of each action.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        A one-hot encoding of each action's type.

    Examples
    --------
    One-hot encode atomic action types per gamestate slot::

        from silly_kicks.atomic.vaep.features import actiontype_onehot, gamestates

        states = gamestates(atomic, nb_prev_actions=3)
        feats = actiontype_onehot(states)
        # feats has 33 boolean columns per slot (one per atomic action type).
    """
    X = {}
    for type_id, type_name in enumerate(atomicspadl.actiontypes):
        col = "actiontype_" + type_name
        X[col] = actions["type_id"] == type_id
    return pd.DataFrame(X, index=actions.index)


@simple
def location(actions: Actions) -> Features:
    """Get the location where each action started.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        The 'x' and 'y' location of each action.

    Examples
    --------
    Extract atomic location features per gamestate slot::

        from silly_kicks.atomic.vaep.features import gamestates, location

        states = gamestates(atomic, nb_prev_actions=3)
        feats = location(states)
        # feats has columns 'x_a0', 'y_a0', 'x_a1', 'y_a1', 'x_a2', 'y_a2'.
    """
    return actions[["x", "y"]]  # type: ignore[reportReturnType]


_goal_x = atomicspadl.field_length
_goal_y = atomicspadl.field_width / 2


@simple
def polar(actions: Actions) -> Features:
    """Get the polar coordinates of each action's start location.

    The center of the opponent's goal is used as the origin.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        The 'dist_to_goal' and 'angle_to_goal' of each action.

    Examples
    --------
    Compute polar features (distance + angle to opponent goal) per slot::

        from silly_kicks.atomic.vaep.features import gamestates, polar

        states = gamestates(atomic, nb_prev_actions=3)
        feats = polar(states)
        # feats has columns 'dist_to_goal_a0', 'angle_to_goal_a0', etc.
    """
    polardf = pd.DataFrame(index=actions.index)
    dx = (_goal_x - actions["x"]).abs().to_numpy()
    dy = (_goal_y - actions["y"]).abs().to_numpy()
    polardf["dist_to_goal"] = np.sqrt(dx**2 + dy**2)
    with np.errstate(divide="ignore", invalid="ignore"):
        polardf["angle_to_goal"] = np.nan_to_num(np.arctan(dy / dx))
    return polardf


@simple
def movement_polar(actions: Actions) -> Features:
    """Get the distance covered and direction of each action.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        The distance covered ('mov_d') and direction ('mov_angle') of each action.

    Examples
    --------
    Compute per-action movement magnitude + angle features per slot::

        from silly_kicks.atomic.vaep.features import gamestates, movement_polar

        states = gamestates(atomic, nb_prev_actions=3)
        feats = movement_polar(states)
        # feats has 'mov_d_a0' (metres) and 'mov_angle_a0' (radians) per slot.
    """
    mov = pd.DataFrame(index=actions.index)
    mov["mov_d"] = np.sqrt(actions.dx**2 + actions.dy**2)
    with np.errstate(divide="ignore", invalid="ignore"):
        mov["mov_angle"] = np.arctan2(actions.dy, actions.dx)
        mov.loc[actions.dy == 0, "mov_angle"] = 0  # fix float errors
    return mov


@simple
def direction(actions: Actions) -> Features:
    """Get the direction of the action as components of the unit vector.

    Parameters
    ----------
    actions : Actions
        The actions of a game.

    Returns
    -------
    Features
        The x-component ('dx') and y-compoment ('mov_angle') of the unit
        vector of each action.

    Examples
    --------
    Compute per-action unit-direction vector features per slot::

        from silly_kicks.atomic.vaep.features import direction, gamestates

        states = gamestates(atomic, nb_prev_actions=3)
        feats = direction(states)
        # feats has 'dx_a0' and 'dy_a0' (unit-length components, 0 if static).
    """
    mov = pd.DataFrame(index=actions.index)
    totald = np.sqrt(actions.dx**2 + actions.dy**2)
    for d in ["dx", "dy"]:
        # we don't want to give away the end location,
        # just the direction of the ball
        # We also don't want to divide by zero
        mov[d] = actions[d].mask(totald > 0, actions[d] / totald)

    return mov


def goalscore(gamestates: GameStates) -> Features:
    """Get the number of goals scored by each team after the action.

    Parameters
    ----------
    gamestates : GameStates
        The gamestates of a game.

    Returns
    -------
    Features
        The number of goals scored by the team performing the last action of the
        game state ('goalscore_team'), by the opponent ('goalscore_opponent'),
        and the goal difference between both teams ('goalscore_diff').

    Examples
    --------
    Compute the cumulative-goalscore context feature on a gamestate sequence::

        from silly_kicks.atomic.vaep.features import gamestates, goalscore

        states = gamestates(atomic, nb_prev_actions=3)
        feats = goalscore(states)
        # feats has 'goalscore_team', 'goalscore_opponent', 'goalscore_diff'.
    """
    actions = gamestates[0]
    teamA = actions["team_id"].values[0]
    goals = actions.type_name == "goal"
    owngoals = actions["type_name"].str.contains("owngoal")

    teamisA = actions["team_id"] == teamA
    teamisB = ~teamisA
    goalsteamA = (goals & teamisA) | (owngoals & teamisB)
    goalsteamB = (goals & teamisB) | (owngoals & teamisA)
    goalscoreteamA = goalsteamA.cumsum() - goalsteamA
    goalscoreteamB = goalsteamB.cumsum() - goalsteamB

    scoredf = pd.DataFrame(index=actions.index)
    scoredf["goalscore_team"] = (goalscoreteamA * teamisA) + (goalscoreteamB * teamisB)
    scoredf["goalscore_opponent"] = (goalscoreteamB * teamisA) + (goalscoreteamA * teamisB)
    scoredf["goalscore_diff"] = scoredf["goalscore_team"] - scoredf["goalscore_opponent"]
    return scoredf


def _atomic_xt_delta_map(a0: pd.DataFrame, model) -> dict[tuple, float]:
    """Per-action xT delta on the unshifted atomic stream, keyed by (game,period,action_id).

    Type-aware success (dribble intrinsic; pass/cross next-atom-``receival``); reuses
    ``model.rate`` via a synthesized standard-SPADL frame. See NOTICE for citations.

    Parameters
    ----------
    a0 : pd.DataFrame
        The unshifted atomic action stream (``states[0]``).
    model : ExpectedThreat
        A fitted xT model (duck-typed: ``.rate`` / ``.xT``).

    Returns
    -------
    dict[tuple, float]
        ``(game_id, period_id, action_id) -> xT delta`` for move atoms.
    """
    move_names = ("pass", "dribble", "cross")
    move_ids = [atomicspadl.actiontype_id[n] for n in move_names]  # atomic ids
    type_id = a0["type_id"].to_numpy()
    is_move = np.isin(type_id, move_ids)
    if not is_move.any():
        return {}

    # Next-atom success for pass/cross (within same game+period); dribble always successful.
    n = len(a0)
    next_type = np.full(n, -1, dtype=type_id.dtype)
    next_type[:-1] = type_id[1:]
    game = a0["game_id"].to_numpy()
    period = a0["period_id"].to_numpy()
    next_game = np.full(n, -1, dtype=game.dtype)
    next_game[:-1] = game[1:]
    next_period = np.full(n, -1, dtype=period.dtype)
    next_period[:-1] = period[1:]
    same_gp = (next_game == game) & (next_period == period)

    receival_id = atomicspadl.actiontype_id["receival"]
    dribble_id = atomicspadl.actiontype_id["dribble"]
    is_dribble = type_id == dribble_id
    is_passcross = is_move & ~is_dribble
    success = is_dribble | (is_passcross & same_gp & (next_type == receival_id))

    move_idx = np.flatnonzero(is_move)
    sub = a0.iloc[move_idx]
    synth = pd.DataFrame(
        {
            # Map atomic move type -> standard move type by NAME. The ids currently coincide
            # (pass/dribble/cross == 0/21/1 in both configs), but keep the name-map deliberate:
            # do NOT "simplify" to raw ids -- that would silently break if a future config
            # (GS / SkillCorner) ever renumbers.
            "type_id": [stdspadl.actiontype_id[atomicspadl.actiontypes[int(t)]] for t in type_id[move_idx]],
            "result_id": np.where(success[move_idx], stdspadl.result_id["success"], stdspadl.result_id["fail"]),
            "start_x": sub["x"].to_numpy(dtype=float),
            "start_y": sub["y"].to_numpy(dtype=float),
            "end_x": (sub["x"] + sub["dx"]).to_numpy(dtype=float),
            "end_y": (sub["y"] + sub["dy"]).to_numpy(dtype=float),
        }
    )
    # NOTE: synth feeds atomic (x, y) / (x+dx, y+dy) into model.rate(), which bins via
    # silly_kicks.spadl.config field dims. Correct because atomic SPADL shares the standard
    # 105x68 pitch frame (atomicspadl.field_length/width == spadl.config.field_length/width).
    deltas = model.rate(synth)  # ndarray len(move_idx); NaN for failed/NaN-coord rows
    # int-cast the key parts: gamestates' shift() can upcast id columns int->float on slots
    # a1/a2, so building/looking-up keys as ints keeps them comparable regardless of dtype.
    keys = [
        (int(g), int(p), int(a)) for g, p, a in zip(sub["game_id"], sub["period_id"], sub["action_id"], strict=False)
    ]
    # dict() collapses duplicate keys (e.g. the all-zero dummy used by feature_column_names),
    # so this never raises on non-unique keys the way a reindex/merge would.
    return dict(zip(keys, deltas, strict=False))


def xt_xfns(*, model=None) -> list[FeatureTransfomer]:
    """Atomic mirror of the standard ``xt_xfns``: emits ``xt__<model.method>_a{i}``.

    Type-aware success + ``model.rate`` reuse via a synthesized standard frame; maps to
    slots by the composite ``(game_id, period_id, action_id)`` key. Opt-in (not in any
    default list). See ``silly_kicks.vaep.features.expected_threat.xt_xfns`` and NOTICE.

    Parameters
    ----------
    model : ExpectedThreat
        A fitted xT model. ``str`` (future bundled variant) and ``None`` raise.

    Returns
    -------
    list[FeatureTransfomer]
        A one-element list holding the transformer.

    Raises
    ------
    ValueError, NotImplementedError, NotFittedError
        If ``model`` is not a fitted ExpectedThreat.

    Examples
    --------
    Opt in to atomic xT as a VAEP feature::

        from silly_kicks.atomic.vaep.features import xt_xfns

        xfns = [afs.location, *xt_xfns(model=fitted_xt)]
    """
    if isinstance(model, str):
        raise NotImplementedError(
            "xt_xfns: bundled xT grid variants are not shipped yet; pass a fitted ExpectedThreat."
        )
    if model is None:
        raise ValueError("xt_xfns requires a fitted ExpectedThreat (model=...).")
    if not np.any(model.xT):
        raise NotFittedError("xt_xfns requires a fitted ExpectedThreat; call model.fit(actions) first.")

    col = f"xt__{model.method}"

    def _xt(states: GameStates) -> Features:
        a0 = states[0]
        delta_map = _atomic_xt_delta_map(a0, model)
        out = pd.DataFrame(index=a0.index)
        for i, slot in enumerate(states):
            # int-cast to match the int keys built in _atomic_xt_delta_map (shift() may have
            # upcast these id columns to float on slots a1/a2; boundary rows are filled, never NaN).
            keys = [
                (int(g), int(p), int(a))
                for g, p, a in zip(slot["game_id"], slot["period_id"], slot["action_id"], strict=False)
            ]
            out[f"{col}_a{i}"] = pd.Series([delta_map.get(k, np.nan) for k in keys], index=slot.index)
        return out

    _xt.__name__ = col
    return [_xt]
